### ISSUE TITLE
OpenMP on Spike

### ISSUE THREAD

**Issue by ashuthosh-mr** [riscv/riscv-isa-sim#1015]
Hi, 
I want to run a OpenMP code on Spike. I believe I need a Linux on Spike in SMP mode. So, could someone please help me with how I can get it up running?
Thank you

**Comment by ghost** [comment]
Did you figure it out @ashuthosh-mr? Would be a great resource for community if you did so.

**Comment by ashuthosh-mr** [comment]
No. But I got it running on arty a7 board. https://github.com/litex-hub/linux-on-litex-vexriscv/issues/281
