### ISSUE TITLE
Issue in pmpaddr0

### ISSUE THREAD

**Issue by UmerShahidengr** [riscv/riscv-isa-sim#1019]
Hello,
I wrote a test in riscof environment to verify the lock-bit functionality of PMP. If PMP entry i is locked, writes to pmpicfg and pmpaddri should have been ignored according to RISC-V privilege manual.
In the test, I locked the lock-bit of pmpcfg0 register in m-mode, and try to write pmpcfg0, pmpaddr0, pmpaddr1.. All these write accesses should have been blocked but pmpaddr0 is getting updated in DUT-Spike model.
The test file, DUT-Spike-Signature file, and REF-Sail-Signature file are attached.

[PMP-CFG-reg_locked.txt](https://github.com/riscv-software-src/riscv-isa-sim/files/8822313/PMP-CFG-reg_locked.txt)

[DUT-Spike-signature.txt](https://github.com/riscv-software-src/riscv-isa-sim/files/8822309/DUT-Spike-signature.txt)

[Reference-sail_c_simulator-signature.txt](https://github.com/riscv-software-src/riscv-isa-sim/files/8822305/Reference-sail_c_simulator-signature.txt)

**Comment by aswaterman** [comment]
Please provide an easy way for us to replicate this bug; and, if you're convinced it is, in fact, a bug, we request that you supply a pull request to fix it.

**Comment by UmerShahidengr** [comment]
In order to replicate this error, you may run this simple code,

//////////////////// TEST START HERE  /////////////////////////////////////////////

    	li	a5,-1                   // PUT 0xFFFFFFFF

	
	csrw pmpcfg0, a5		// WRITE pmpcfg0 with ALL 1s, Locked the lock-bit [7,15,23,31]
	nop
	
	csrr a5, pmpcfg0		// READ pmpcfg0		

	// Verify that LOCKED bits are HIGH by displaying it in debugger
	

	// TRY TO WRITE ADDRESS REGISTER. THIS WRITE SHOULD HAVE BEEN IGNORED 
	csrw pmpaddr0, a5		// WRITE pmpaddr0 with some other values
	nop
	
	csrr a5, pmpaddr0		// READ pmpaddr0		

	// The updated write should have been ignored and should have given the previously saved value!!!

**Comment by aswaterman** [comment]
That's not an easy way for us to replicate the bug.  Please provide an ELF and a command-line argument.

**Comment by scottj97** [comment]
I'm sure that PMP locking is not completely broken. Here's a log (of a proprietary test, sorry) created from the current master (901fedb22cbf5de22fab60a6c5d7236e350ecf64):
```
core   0: 0x00000000800021b2 (0x3a011073) csrw    pmpcfg0, sp
core   0: 3 0x00000000800021b2 (0x3a011073) c928_pmpcfg0 0x0000009800000000
core   0: 0x00000000800021b6 (0x5ff00193) li      gp, 1535
core   0: 3 0x00000000800021b6 (0x5ff00193) x3  0x00000000000005ff
core   0: 0x00000000800021ba (0x3b019073) csrw    pmpaddr0, gp
core   0: 3 0x00000000800021ba (0x3b019073) c944_pmpaddr0 0x00000000000005ff
core   0: 0x00000000800021be (0x3b119073) csrw    pmpaddr1, gp
core   0: 3 0x00000000800021be (0x3b119073) c945_pmpaddr1 0x00000000000005ff
core   0: 0x00000000800021c2 (0x3b219073) csrw    pmpaddr2, gp
core   0: 3 0x00000000800021c2 (0x3b219073) c946_pmpaddr2 0x00000000000005ff
core   0: 0x00000000800021c6 (0x3b319073) csrw    pmpaddr3, gp
core   0: 3 0x00000000800021c6 (0x3b319073) c947_pmpaddr3 0x00000000000005ff
core   0: 0x00000000800021ca (0x3b419073) csrw    pmpaddr4, gp
core   0: 3 0x00000000800021ca (0x3b419073)
core   0: 0x00000000800021ce (0x3b519073) csrw    pmpaddr5, gp
core   0: 3 0x00000000800021ce (0x3b519073) c949_pmpaddr5 0x00000000000005ff
core   0: 0x00000000800021d2 (0x3b619073) csrw    pmpaddr6, gp
core   0: 3 0x00000000800021d2 (0x3b619073) c950_pmpaddr6 0x00000000000005ff
core   0: 0x00000000800021d6 (0x3b719073) csrw    pmpaddr7, gp
core   0: 3 0x00000000800021d6 (0x3b719073) c951_pmpaddr7 0x00000000000005ff
core   0: 0x00000000800021da (0x3b819073) csrw    pmpaddr8, gp
core   0: 3 0x00000000800021da (0x3b819073) c952_pmpaddr8 0x00000000000005ff
core   0: 0x00000000800021de (0x3b919073) csrw    pmpaddr9, gp
core   0: 3 0x00000000800021de (0x3b919073) c953_pmpaddr9 0x00000000000005ff
core   0: 0x00000000800021e2 (0x3ba19073) csrw    pmpaddr10, gp
core   0: 3 0x00000000800021e2 (0x3ba19073) c954_pmpaddr10 0x00000000000005ff
core   0: 0x00000000800021e6 (0x3bb19073) csrw    pmpaddr11, gp
core   0: 3 0x00000000800021e6 (0x3bb19073) c955_pmpaddr11 0x00000000000005ff
core   0: 0x00000000800021ea (0x3bc19073) csrw    pmpaddr12, gp
core   0: 3 0x00000000800021ea (0x3bc19073) c956_pmpaddr12 0x00000000000005ff
core   0: 0x00000000800021ee (0x3bd19073) csrw    pmpaddr13, gp
core   0: 3 0x00000000800021ee (0x3bd19073) c957_pmpaddr13 0x00000000000005ff
core   0: 0x00000000800021f2 (0x3be19073) csrw    pmpaddr14, gp
core   0: 3 0x00000000800021f2 (0x3be19073) c958_pmpaddr14 0x00000000000005ff
core   0: 0x00000000800021f6 (0x3bf19073) csrw    pmpaddr15, gp
core   0: 3 0x00000000800021f6 (0x3bf19073) c959_pmpaddr15 0x00000000000005ff
core   0: 0x00000000800021fa (0x3b002273) csrr    tp, pmpaddr0
core   0: 3 0x00000000800021fa (0x3b002273) x4  0x00000000000005ff
core   0: 0x00000000800021fe (0x3b102273) csrr    tp, pmpaddr1
core   0: 3 0x00000000800021fe (0x3b102273) x4  0x00000000000005ff
core   0: 0x0000000080002202 (0x3b202273) csrr    tp, pmpaddr2
core   0: 3 0x0000000080002202 (0x3b202273) x4  0x00000000000005ff
core   0: 0x0000000080002206 (0x3b302273) csrr    tp, pmpaddr3
core   0: 3 0x0000000080002206 (0x3b302273) x4  0x00000000000005ff
core   0: 0x000000008000220a (0x3b402273) csrr    tp, pmpaddr4
core   0: 3 0x000000008000220a (0x3b402273) x4  0x0000000000000000
core   0: 0x000000008000220e (0x3b502273) csrr    tp, pmpaddr5
core   0: 3 0x000000008000220e (0x3b502273) x4  0x00000000000005ff
core   0: 0x0000000080002212 (0x3b602273) csrr    tp, pmpaddr6
core   0: 3 0x0000000080002212 (0x3b602273) x4  0x00000000000005ff
core   0: 0x0000000080002216 (0x3b702273) csrr    tp, pmpaddr7
core   0: 3 0x0000000080002216 (0x3b702273) x4  0x00000000000005ff
core   0: 0x000000008000221a (0x3b802273) csrr    tp, pmpaddr8
core   0: 3 0x000000008000221a (0x3b802273) x4  0x00000000000005ff
core   0: 0x000000008000221e (0x3b902273) csrr    tp, pmpaddr9
core   0: 3 0x000000008000221e (0x3b902273) x4  0x00000000000005ff
core   0: 0x0000000080002222 (0x3ba02273) csrr    tp, pmpaddr10
core   0: 3 0x0000000080002222 (0x3ba02273) x4  0x00000000000005ff
core   0: 0x0000000080002226 (0x3bb02273) csrr    tp, pmpaddr11
core   0: 3 0x0000000080002226 (0x3bb02273) x4  0x00000000000005ff
core   0: 0x000000008000222a (0x3bc02273) csrr    tp, pmpaddr12
core   0: 3 0x000000008000222a (0x3bc02273) x4  0x00000000000005ff
core   0: 0x000000008000222e (0x3bd02273) csrr    tp, pmpaddr13
core   0: 3 0x000000008000222e (0x3bd02273) x4  0x00000000000005ff
core   0: 0x0000000080002232 (0x3be02273) csrr    tp, pmpaddr14
core   0: 3 0x0000000080002232 (0x3be02273) x4  0x00000000000005ff
core   0: 0x0000000080002236 (0x3bf02273) csrr    tp, pmpaddr15
core   0: 3 0x0000000080002236 (0x3bf02273) x4  0x00000000000005ff
```
You can see at pc=0x800021ca that `pmpaddr4` is not written, and this is confirmed at pc=0x8000220a when the readback shows it still contains 0.

**Comment by scottj97** [comment]
I suspect what you are seeing is not broken locking, but an unexpected initial value in `pmpaddr0`. See [this code](https://github.com/riscv-software-src/riscv-isa-sim/blob/901fedb22cbf5de22fab60a6c5d7236e350ecf64/riscv/processor.cc#L503-L508) that initializes `pmpaddr0` with a different value than the others.

**Comment by aswaterman** [comment]
(which, by the way, is legal, because of the subordinate clause in https://github.com/riscv/riscv-isa-manual/blob/3e7b389772b5d909b3dfa2db57e60f73329e5721/src/machine.tex#L2883-L2884)

**Comment by UmerShahidengr** [comment]
Thanks @scottj97 . It was indeed an issue of unexpected initial values in different models. Thanks @aswaterman for your swift response.
