### ISSUE TITLE
why cannot open pk?

### ISSUE THREAD

**Issue by yuyang-ok** [riscv/riscv-isa-sim#1028]
~~~
yuyang@yuyang-vmwarevirtualplatform:~/projects/riscv-gcc-test$ ../riscv-isa-sim/build/spike  pk ./a.out 
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open pk (did you misspell it? If VCS, did you forget +permissive/+permissive-off?)
~~~

**Comment by yuyang-ok** [comment]
[hello.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/8882940/hello.zip)

**Comment by aswaterman** [comment]
Did you install pk?

**Comment by yuyang-ok** [comment]
pk?? what is pk? I think pk is a command argument. no need to install.

**Comment by aswaterman** [comment]
pk is a program that you’re attempting to run but that you don’t have installed. You can find it here: https://github.com/riscv-software-src/riscv-pk

Closing because there’s no Spike bug evident.
