### ISSUE TITLE
RV32 csrw to mstatus erroneously clears mstatush

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-sim#1044]
On RV32, a `csrw mstatus` should not touch the bits in `mstatush`, but ever since we first added writable bits in `mstatush` (in dac0d3ce7161d480c06b8a19675f66ae636bc20d for #812) this has been broken. A `csrw mstatus` will erroneously clear the writable bits in `mstatush`.

Note that `mstatush` only has writable bits if hypervisor is enabled.

**Comment by aswaterman** [comment]
Good catch.
