### ISSUE TITLE
Bump submodule reference

### ISSUE THREAD

**Issue by michael-roe** [riscv/riscv-isa-sim#1048]
I may be misunderstanding something here, but I think you need to update the submodule reference to riscv-isa-sim to pick up this fix:

commit b3855682c2d744c613d2ffd6b53e3f021ecea4f3
Author: Schuyler Eldridge <schuyler.eldridge@ibm.com>
Date:   Wed May 6 17:53:18 2020 -0400

**Comment by aswaterman** [comment]
Posted on wrong repo’s issue tracker?

**Comment by scottj97** [comment]
Closing as this does not appear to be a riscv-isa-sim issue.
