### ISSUE TITLE
When sfence executed in User mode with sv39 VM-System, the core get into a deadlock.

### ISSUE THREAD

**Issue by naveen126** [riscv/riscv-isa-sim#1052]
Hi Sir,
I have an ASM case described as bellow.
In the start section of asm code, some steps are as the following.
(1) All delegation config, including illegal instruction exception,  has been enabled in start section;
(2) The text section has been set with pte.U == 1, and the supervisor handler locates in text section;
(3) Set mstatus.prv == 0 to enter into U mode.

In the main code of user-mode, there is a "sfence.vma".
Now the core meet the sfence in User-Mode, it triggers an illegal instruction exception; Then the core switches into S-Mode.
But in the S-Mode, when fetching instructions, the core finds out PTE.U == 1, so it gets an instruction page fault.
Now, the core has a deadlock. 

So, I have three questions to solve this issue.
1, How to invalidate tlb buffer in User Mode?
2, Does the code of User need separate config for VM-system?
3, Does the exception vector table have its own   config for VM-system?

Thanks for your help.

**Comment by aswaterman** [comment]
This is more of a software question than an ISA-spec question, so going forward, I suggest you use other resources (like the sw-dev mailing list https://groups.google.com/a/groups.riscv.org/g/sw-dev).

SFENCE.VMA is illegal in U-mode.  Normally, U-mode uses system calls to request that S-mode make changes to its virtual-memory configuration, and then S-mode executes SFENCE.VMA.
