### ISSUE TITLE
Is 'require_vector_novtype'  correct for  vmvnfr.v instruction now ?

### ISSUE THREAD

**Issue by xiongtao2022** [riscv/riscv-isa-sim#1078]
I have seen  that vmvnfr_v.h  was fixed to take vsew into account,  but it still use 'require_vector_novtype' function , which won't raise a trap if vill is set.  As spec said, "If the vill bit is set, then any attempt to execute a vector instruction that depends upon vtype will raise an illegal-instruction exception". 
Also, "These instructions are intended to aid compilers to shuffle vector registers without needing to know or change vl or vtype." seems contradictory now.

**Comment by aswaterman** [comment]
Agreed this is a bug.  See https://github.com/riscv-software-src/riscv-isa-sim/pull/1079

I actually disagree with your comment that the spec sentence is contradictory, as should be assumed that in normal operation, `vill`=0.  If software sets up `vill`=1 before calling another function, I think trapping is fine.  The important thing is that `vmv<nf>r.v` has the same architecturally visible effect regardless of SEW/LMUL when `vill`=0.

**Comment by xiongtao2022** [comment]
Sorry, I didn't describe last sentence clearly. I mean that vmvnfr.v needs to know vsew in vtype when vstart !=0, but spec said    "without needing to know vtype", that confuse me.
