### ISSUE TITLE
vestvli - unrecognized opcode vsetvli a5,a5,e32

### ISSUE THREAD

**Issue by balaji-ch** [riscv/riscv-isa-sim#1090]
Hi
I tried the following code 
```c
#include <stdio.h>

void main(){
    //unsigned long vlenb;
    //asm volatile ("csrr %0, vlenb" : "=r" (vlenb));  // this works though
    unsigned long  vl = 0;
    unsigned long  elements = 128;
    asm volatile ("vsetvli %0, %1, e32" : "=r"(vl) : "r"(elements));
    printf("vl init = %d\n",vl);
}
```
with the below build command
` riscv64-unknown-elf-gcc -o hello hello.c`

I get the following error
 **hello.c:9: Error: unrecognized opcode vsetvli a5,a5,e32** 

What is the correct way of using vsetvli ?

PS:
I used the prebuilt tool chain riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz

**Comment by balaji-ch** [comment]
Figured out the correct way

**Build**
```sh
riscv64-unknown-elf-gcc -march=rv64gcv -o hello hello.c
```

**Run**
```sh
spike --varch=vlen:128,elen:32 --isa=rv64gcv pk hello
```

**Comment by aswaterman** [comment]
Indeed, the error you encountered has nothing to do with Spike.

**Comment by balaji-ch** [comment]
It would be better if this is added to the README.md of Spike RISC-V ISA Simulator
