### ISSUE TITLE
Can we support arrow keys in the spike debug mode

### ISSUE THREAD

**Issue by XiaJin-RiVAI** [riscv/riscv-isa-sim#1092]
Hi everybody,
As Spike is already very useful while debugging RISCV apps in debug mode, still I think maybe it could be more convenient if we support the function of using the arrow keys to move the cursor and trace back the history command in the debug mode. And I have already implemented it locally. But unfortunately, there is format problem to just put the patch in here.
Is there a possible to submit this patch?
Sincerely Thanks!

**Comment by scottj97** [comment]
You can submit a patch using a [Pull Request](https://docs.github.com/en/pull-requests).

In this case, why not use a common package like [GNU Readline](https://tiswww.cwru.edu/php/chet/readline/rltop.html)?

**Comment by aswaterman** [comment]
Unfortunately, Readline's license is incompatible.

**Comment by scottj97** [comment]
[Alternatives](https://stackoverflow.com/questions/17982633/lightweight-gnu-readline-alternative)...replxx looks promising

**Comment by XiaJin-RiVAI** [comment]
@scottj97 Thanks for your reply. So what you suggest is to migrate the [replxx](https://github.com/AmokHuginnsson/replxx) into the spike and call it during the debug mode? Am I get it right?

**Comment by XiaJin-RiVAI** [comment]
@scottj97 @aswaterman Here is the [pull request](https://github.com/riscv-software-src/riscv-isa-sim/pull/1099), please review. If you have any concern or suggestion, please feel free to info me. I'm willing to revise and resubmit. Thank you.

**Comment by XiaJin-RiVAI** [comment]
As the [pull request](https://github.com/riscv-software-src/riscv-isa-sim/pull/1099) has been merged, so close this issue. Thank you @scottj97 @aswaterman again for reviewing.
