### ISSUE TITLE
Redeclaration in encoding.h and debug_defines.h

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-isa-sim#1108]
There are redeclarations of CSR fields in encoding.h and debug_defines.h. For instance, the mcontrol.select is declared by both encoding.h and debug_defines.h but with different names, MCONTROL_SELECT and CSR_MCONTROL_SELECT. Thus, there are two naming conventions for a CSR field.

The current source code uses both naming conventions, e.g., CSR_MCONTROL_HIT and MCONTROL_SELECT. Do we prefer to use a specific naming convention for consistency? Or do we accept both of the naming conventions?

**Comment by aswaterman** [comment]
encoding.h is an auto-generated source of truth, so we should generally use its definitions and avoid manually duplicating them into other files.

**Comment by YenHaoChen** [comment]
Thank you

**Comment by timsifive** [comment]
debug_defines.h is *also* an auto-generated source of truth. (It is in fact generated from the exact same files that define the registers/bits in the debug spec, so will always match the spec.) I prefer to use it for debug registers. (It only contains debug-related defines.)

**Comment by YenHaoChen** [comment]
Thank you, @timsifive, for the further comment.
