### ISSUE TITLE
Issues printing commit logs

### ISSUE THREAD

**Issue by torresramon1** [riscv/riscv-isa-sim#1110]
I did the ../configure --enable-commitlog --prefix=$RISCV
When I run my code using , spike --log-commits pk a.out
I get the error -- Commit logging support has not been properly enabled; please re-build the riscv-isa-sim project using "configure --enable-commitlog".

What Am I doing wrong?

**Comment by scottj97** [comment]
Are you doing an incremental build or a clean build? Incremental probably won't rebuild enough. Try deleting your build directory first, so you get a clean build.

**Comment by torresramon1** [comment]
> Are you doing an incremental build or a clean build? Incremental probably won't rebuild enough. Try deleting your build directory first, so you get a clean build.

I don't know If I am missing a command, but I deleted build directory created it again, went in it and ran the command ../configure --enable-commitlog --prefix=$RISCV and that is it. I then ran my a.out with the same command as above and I get the same error.

**Comment by scottj97** [comment]
> I don't know If I am missing a command, but I deleted build directory created it again, went in it and ran the command ../configure --enable-commitlog --prefix=$RISCV and that is it. I then ran my a.out with the same command as above and I get the same error.

I assume you ran `make` too? After `configure`? Are you sure you're running `./spike` and not picking up another spike somewhere in your $PATH?

**Comment by torresramon1** [comment]
> > I don't know If I am missing a command, but I deleted build directory created it again, went in it and ran the command ../configure --enable-commitlog --prefix=$RISCV and that is it. I then ran my a.out with the same command as above and I get the same error.
> 
> I assume you ran `make` too? After `configure`? Are you sure you're running `./spike` and not picking up another spike somewhere in your $PATH?

I completely deleted my spike, when I run spike it says command not found. I cloned the repo once again, went in it made build directory, went inside build and ran the commands 
../configure --enable-commitlog --prefix=$RISCV
../configure --prefix=$RISCV
make

in that order exactly, now when I try to run my code using spike pk a.out it says spike command not found.
It might be an issue of it not being on my path, what should I add to my path so that the spike command works?

**Comment by scottj97** [comment]
Until you run `make install` it only lives in the current directory. So you'd want to run `./spike`

(Note: not a good idea to add `.` to your $PATH.)

**Comment by scottj97** [comment]
@rtorre32 can we close this as solved?

**Comment by torresramon1** [comment]
> @rtorre32 can we close this as solved?

Yes, Thanks!
