### ISSUE TITLE
how to distinguish c.add and c.jalr?

### ISSUE THREAD

**Issue by yangbonis** [riscv/riscv-isa-sim#1113]
https://riscv.org/wp-content/uploads/2015/11/riscv-compressed-spec-v1.9.pdf
Table 1.6 of above manual show [2:6] field of c.add is not zero, and [2:6] field of c.jalr is zero.

#define MATCH_C_JALR 0x9002
#define MASK_C_JALR  0xf07f
#define MATCH_C_ADD 0x9002
#define MASK_C_ADD  0xf003

In encoding.h MASK and MATCH how to distinguish c.add and c.jalr?

**Comment by aswaterman** [comment]
IIRC, the answer is that, if the matches are equal, the more restrictive mask (JALR) is considered first, and the less restrictive mask (ADD) is checked only if that fails.

**Comment by yangbonis** [comment]
> IIRC, the answer is that, if the matches are equal, the more restrictive mask (JALR) is considered first, and the less restrictive mask (ADD) is checked only if that fails.

oh, i see. build_opcode_map sort array by match.
