### ISSUE TITLE
"Warning (interrupt_provider): /soc/plic@c000000: Missing #address-cells in interrupt provider"

### ISSUE THREAD

**Issue by SimonSapin** [riscv/riscv-isa-sim#1135]
Running 04a912d8c30f70dba060a8c2cf1d92afa5067e23 with dtc 1.6.1 produces a warning at start-up, seemingly every time:

```
<stdin>:48.24-56.7: Warning (interrupt_provider): /soc/plic@c000000: Missing #address-cells in interrupt provider
```

This looks similar to https://github.com/riscv-software-src/riscv-isa-sim/issues/784

**Comment by aswaterman** [comment]
Indeed, analogous to #784.  Fixed.
