### ISSUE TITLE
Is there a developer's manual?

### ISSUE THREAD

**Issue by KevinKBytes** [riscv/riscv-isa-sim#1139]
Currently starting development on a modified version of Spike (Force-riscv), where they patch an old fixed version of Spike to add APIs and package it into a shared object (to interact with an Random Instruction Generator). In order to continue development on Force, I'd like to understand more on how Spike works.

Is there any documentation available on how Spike works? Any pointers would be deeply appreciated.

**Comment by aswaterman** [comment]
No API docs. What you see is what you get, I’m afraid.
