### ISSUE TITLE
Spec for TLB

### ISSUE THREAD

**Issue by KevinKBytes** [riscv/riscv-isa-sim#1144]
I see that TLBs are simulated in spike, but I cant find the documentation for TLBs in the RISCV specs.
Could anybody point to me where the specs for RISCV/Spike TLB are defined?

**Comment by aswaterman** [comment]
They are specified implicitly. Please read the privileged architecture spec and note the definition of the SFENCE.VMA instruction.

In general, this is not a good forum to ask ISA questions.
