### ISSUE TITLE
Using Spike as a reference model for verification

### ISSUE THREAD

**Issue by AshvinVaidyanathan** [riscv/riscv-isa-sim#1185]
How exactly does one use this simulator as a golden reference model? I am able to run my test codes on spike and getting the desired results, by checking individual register and memory values on debug mode. However creating a log using the `--log=<filename>` just gives an empty text file. How can I use Spike to create a reference log for simulation.

**Comment by scottj97** [comment]
Did you build Spike using `configure --enable-commitlog`? Did you run using both `-l --log-commits`?
