### ISSUE TITLE
v extension, vsetvl instruction with rd=x0 and rs1=x0

### ISSUE THREAD

**Issue by Madman-Hugo** [riscv/riscv-isa-sim#1199]
<img width="723" alt="a458950fcc415deae747910a69b015a2" src="https://user-images.githubusercontent.com/13159359/209773437-db0b3f35-c79d-47c1-9182-fce3d8887099.png">
According to V1.0 vector spec, for and instruction like vsetvl x0, x0, x3, currently it can only be used when VLMAX and hence vl is not actually changed.
But from spike's code, function set_vl, we could see that:
<img width="602" alt="3c709de6e864407266fe91ee11549ff5" src="https://user-images.githubusercontent.com/13159359/209774082-b7e6e534-7208-4b2c-b478-4faaad512368.png">
in this condition, vl is the smaller one chosen from vlmax and vl. it seems that the current wat didn't follow the spec.

**Comment by aswaterman** [comment]
Note that the V extension spec describes the behavior for this case as "reserved".  This means that software cannot rely on the result, and that implementation-defined behavior is permitted.  Raising an exception in this case is recommended, not required.
