### ISSUE TITLE
Does spike support assembly code as input？

### ISSUE THREAD

**Issue by dshm** [riscv/riscv-isa-sim#1216]
Does spike support assembly code as input？Such like .s file generated by riscv64-unknown-elf-gcc using -S option and simulate as ‘spike test.s’?  I search a lot on the net and all using cases I found uses executable binary file as input(for example hello.run generated by ‘riscv64-unknown-elf-gcc -o hello.run ./helloworld. c’).

**Comment by aswaterman** [comment]
Nope.  Spike can execute only linked ELF binaries.
