### ISSUE TITLE
terminate called after throwing an instance of 'trap_load_access_fault'

### ISSUE THREAD

**Issue by linuxlonelyeagle** [riscv/riscv-isa-sim#1217]
When I run spike, I get this problem.Terminate called after throwing an instance of 'trap_load_access_fault'.
```
$:spike  a.out
terminate called after throwing an instance of 'trap_load_access_fault'
```
Here is my assembly code.
```
Disassembly of section .text:
00000000000100b0 <main>:
   100b0:       4501                    li      a0,0
   100b2:       8082                    ret
```
If anyone can help me, I would be grateful!Thanks!

**Comment by scottj97** [comment]
Normally a program like this would be run with [`pk` -- proxy kernel](https://github.com/riscv-software-src/riscv-pk).

Bare metal, what Spike models, doesn't have any natural stopping point, so `ret` is likely to go off into the weeds somewhere and execute garbage. `pk` will provide the wrapper than an OS would normally provide in a full system.

**Comment by linuxlonelyeagle** [comment]
> Normally a program like this would be run with [`pk` -- proxy kernel](https://github.com/riscv-software-src/riscv-pk).
> 
> Bare metal, what Spike models, doesn't have any natural stopping point, so `ret` is likely to go off into the weeds somewhere and execute garbage. `pk` will provide the wrapper than an OS would normally provide in a full system.
I checked the information in the link, but it seems that it still has problem when running.
```
$ spike a.out -pk
terminate called after throwing an instance of 'trap_load_access_fault'
```

**Comment by linuxlonelyeagle** [comment]
> > Normally a program like this would be run with [`pk` -- proxy kernel](https://github.com/riscv-software-src/riscv-pk).
> > Bare metal, what Spike models, doesn't have any natural stopping point, so `ret` is likely to go off into the weeds somewhere and execute garbage. `pk` will provide the wrapper than an OS would normally provide in a full system.
> > I checked the information in the link, but it seems that it still has problem when running.
> 
> ```
> $ spike a.out -pk
> terminate called after throwing an instance of 'trap_load_access_fault'
> ```
I think the address of the program is not set properly, you can see the address of the main function is 0000000000000100b0. but I don't know how to change the address of the main function.I don't think the address of the program is set properly, you can see the address of the main function is 0000000000000100b0. But I don't know how to change the address of the main function by riscv64-unknown-elf-gcc.

**Comment by linuxlonelyeagle** [comment]
> Normally a program like this would be run with [`pk` -- proxy kernel](https://github.com/riscv-software-src/riscv-pk).
> 
> Bare metal, what Spike models, doesn't have any natural stopping point, so `ret` is likely to go off into the weeds somewhere and execute garbage. `pk` will provide the wrapper than an OS would normally provide in a full system.

Thank you for your answer, this problem has been solved.
