### ISSUE TITLE
[question] which debug spec version is supported by spike?

### ISSUE THREAD

**Issue by aap-sc** [riscv/riscv-isa-sim#1221]
Hi!

Currently, readme says:

```
+Spike supports the following RISC-V ISA features:
...
+  - Debug v0.14
```

However, I can't find 0.14 anywhere. I've seen the following documents:

- https://riscv.org/wp-content/uploads/2019/03/riscv-debug-release.pdf (which is 0.13.2)
- https://raw.githubusercontent.com/riscv/riscv-debug-spec/master/riscv-debug-stable.pdf (which is deemed to be 1.0)

Could someone clarify the situation? Maybe @aswaterman (since git blame shows you as the author) or @timsifive ?

**Comment by timsifive** [comment]
It should say 1.0 stable. I wouldn't swear that spike does everything according to the spec, but that's the goal.

**Comment by aswaterman** [comment]
If you think we should bump the version number in the README, can you PR it?

**Comment by timsifive** [comment]
Yes, already working on it.

**Comment by aswaterman** [comment]
Thanks!

**Comment by aap-sc** [comment]
@timsifive , thanks for a prompt response!
