### ISSUE TITLE
Using spike with RV32 isa and RoCC extension (--extension)

### ISSUE THREAD

**Issue by JEvSilv** [riscv/riscv-isa-sim#1227]
Hello,

I'm performing spike with flags `--isa=RV32IMAFDC --exentension=<ext>` and it returns: "An illegal instruction was executed!". I found that in the function `rocc_t::get_instructions()` RV32 functions (insns_desc_t) are assigned to `&::illegal_instruction`. So I replaced `&::illegal_instruction` with custom functions (c0-c3) and It worked. Is there some reason to restrict extensions just for RV64?

Thank you!

**Comment by aswaterman** [comment]
When RoCC was originally created, it was only used with RV64, so there’s a historical element.

Spike’s RoCC templates were only designed for RV64 and don’t enforce that data written back to the x-registers is in canonical 32-bit sign-extended form for RV32. There might be other issues along those lines. But I don’t think they’re fundamentally impossible to fix.

**Comment by JEvSilv** [comment]
Thank you for your response!
