### ISSUE TITLE
multi core reservation set support

### ISSUE THREAD

**Issue by hanfeng0114** [riscv/riscv-isa-sim#1258]
Hi

It seems right now the lr/sc reservation set is only supported within one processor/multi threads scenario.
But for multi processors scenario, there is no reservation set implementaion.
If we want to emulate 2 cluster, 4 processors/cluster scenario, we can only set spike as 1 processor with 8 threads?
Is it expected?

Thanks

**Comment by aswaterman** [comment]
Spike's implementation is correct for any number of harts.  How these harts are distributed amongst cores is not relevant to the correctness of the implementation.

The rationale is that Spike executes several instructions on one hart before switching to another hart.  So, it will make progress through any LR/SC sequence that meets the eventuality requirements: https://github.com/riscv/riscv-isa-manual/blob/b39b1bec376ee661bfb05eebe4e7ea781fe4d803/src/a.tex#L280

**Comment by aswaterman** [comment]
(Put another way: if having 4 cores with 2 harts apiece affects LR/SC forward progress vs. having 8 cores with 1 hart apiece, then you might have a bug in your implementation.)

**Comment by hanfeng0114** [comment]
Hi aswaterman,

Thanks for the explanation.
I got the code:
void sim_t::step(size_t n)
{
  for (size_t i = 0, steps = 0; i < n; i += steps)
  {
    steps = std::min(n - i, INTERLEAVE - current_step);
    procs[current_proc]->step(steps);

    current_step += steps;
    if (current_step == INTERLEAVE)
    {
      current_step = 0;
      procs[current_proc]->get_mmu()->yield_load_reservation();
      if (++current_proc == procs.size()) {
        current_proc = 0;
        if (clint) clint->increment(INTERLEAVE / INSNS_PER_RTC_TICK);
        if (ns16550) ns16550->tick();
      }

      host->switch_to();
    }
  }
}
