### ISSUE TITLE
Spike shouldn't trap for whole register moves:vmvnr.

### ISSUE THREAD

**Issue by ajayvreddy** [riscv/riscv-isa-sim#1302]
Spec: 3.4.4 says: vset{i}vl{i} and whole-register loads, stores, and moves do not depend upon vtype.
Spec clarification: https://github.com/riscv/riscv-v-spec/issues/863
I see Spike raise an illegal instruction.
I see two previous issues:  #1079 and #1078 .

`
core   0: 0x000000008002df6c (0x9f01b457) vmv4r.v v8, v16
core   0: exception trap_illegal_instruction, epc 0x000000008002df6c
core   0:           tval 0x000000009f01b457
`
Please comment on the reasoning behind the change for #1079

**Comment by aswaterman** [comment]
There is a contradiction in the spec; the non-normative text is wrong.  Spike is doing what the normative text says it should do.  I've made a PR to delete the offending non-normative text in the vector spec.  https://github.com/riscv/riscv-v-spec/pull/872
