### ISSUE TITLE
2 issue about fcvtmod_w_d.h instruction

### ISSUE THREAD

**Issue by lihrlaoke** [riscv/riscv-isa-sim#1312]
hi , we found 2 issue in fcvtmod_w_d.h file 
1. in fcvtmod_w_d.h line 40, if shift <= -64 , whether do we need to rasie a inexact exception ? due to the frac bit got shifted out 
2. in  fcvtmod_w_d.h line 36 & line 46 , inexact exception and invalid exception can raise together meanwhile , but from IEEE754  description this two exception cannot raise together , same input under fcvt_w_d instruction also only raise  invalid exception

**Comment by aswaterman** [comment]
@ptomsich

**Comment by ptomsich** [comment]
Let me check what is going on here, as I had (thought I had) removed the duplicate exceptions at 36 and 46...

**Comment by lihrlaoke** [comment]
hello，any update about this issue ?

**Comment by ptomsich** [comment]
The issue is confirmed. Will be fixed with a minor update of the Zfa implementation in Spike in the coming days.
