### ISSUE TITLE
Vector Floating-Point Compare Instructions vd index overflow issue

### ISSUE THREAD

**Issue by Madman-Hugo** [riscv/riscv-isa-sim#1325]
for some Vector Floating-Point Compare Instructions like vmfeq.vf instructions

there were 2 &vd defined
![image](https://user-images.githubusercontent.com/13159359/232460173-d89f2277-69f8-4594-9d33-8297aafd2e2e.png)

![image](https://user-images.githubusercontent.com/13159359/232458685-f09f560a-89b5-416a-9907-4a5820a1e2f0.png)

in VFP_VF_PARAMS macro where defined &vd as vector elements while vd shoule be single mask register
for example, if vd is v29, lmum=4, the second define macro may extract an illegal vector register index like v32 which may cause problem.

**Comment by aswaterman** [comment]
I think this is harmless, because this just declares a reference that doesn't actually get dereferenced. But I agree it would be cleaner not to do this.  I'll make a PR.
