### ISSUE TITLE
some entries for fli_q.h are incorrect

### ISSUE THREAD

**Issue by aamartin0000** [riscv/riscv-isa-sim#1327]
Entries 7 and 18-25 do not appear to generate the correct quad-precision values.  If you compare with fli_d.h, you can see the inconsistency.

**Comment by aswaterman** [comment]
@ptomsich Can you handle this?  Entry 7 indeed has the wrong exponent (I didn't check any others).

**Comment by ptomsich** [comment]
Thanks. I'll clean this up together with the fcvtmod issues in the next couple days.

**Comment by aswaterman** [comment]
Thanks!
