### ISSUE TITLE
#define VI_LOOP_NSHIFT_BASE ：require(!(insn.rd() == 0 && P.VU.vflmul > 1)) should be deleted？

### ISSUE THREAD

**Issue by Liuziying04** [riscv/riscv-isa-sim#1330]
`#define VI_LOOP_NSHIFT_BASE \
  VI_GENERAL_LOOP_BASE; \
  VI_LOOP_ELEMENT_SKIP({ \
    require(!(insn.rd() == 0 && P.VU.vflmul > 1)); \
  });
`

VI_GENERAL_LOOP_BASE contains require_vm, which requires that rd≠0.
If rd=0, an exception occurs. 
If rd≠0 and no exception, execute VI_LOOP_ELEMENT_SKIP({ require(!(insn.rd() == 0 && P.VU.vflmul > 1)) }). In this case, （insn.rd() == 0 && P.VU.vflmul > 1) must be equal to 0, there is no need to judge vflmul, this condition is meaningless.

So, does this line need to be deleted?

**Comment by aswaterman** [comment]
`require_vm` does not unconditionally require rd≠0.  It only imposes that requirement if the instruction is masked, i.e., if `v_vm()` is false.  So it's not obvious to me the latter condition is vacuous.

(Even if that weren't the case, the redundant check would be benign.)

**Comment by Liuziying04** [comment]
Thanks！
