### ISSUE TITLE
why is `-g` always enabled for spike

### ISSUE THREAD

**Issue by poemonsense** [riscv/riscv-isa-sim#1331]
I notice from the configure script that, if the compiler accepts `-g`, the Makefile always comes with a `-g` argument to the compiler. Correct me if I'm missing something.

Why does spike do so? I think without `-g` spike could run faster.

**Comment by sifiverobert** [comment]
-g only adds DWARF debug to ELF file. It should not affect generated code at all.

**Comment by poemonsense** [comment]
It produces a quite larger elf file. I think it's better to have a configure option to allow the user to determine whether they want `-g`?

**Comment by aswaterman** [comment]
~That capability already exists: `../configure CFLAGS=-g0`~

Unfortunately, passing `-g0` via CFLAGS doesn't have the right precedence.

**Comment by aswaterman** [comment]
This version suffices, so I'll close the issue as complete: `../configure CXXFLAGS=-g0`

(It only affects the C++ objects, but that's the vast majority.  Additionally adding `CFLAGS=-g0` to suppress debug symbols in the C objects has only a tiny effect.)

**Comment by poemonsense** [comment]
Passing `-g0` from compiling flags works. Thanks.
