### ISSUE TITLE
VAMOOREI32.V not taking Illegal instruction exception

### ISSUE THREAD

**Issue by Abdul-Vasan** [riscv/riscv-isa-sim#1334]
I am running spike with the following options: `--isa=rv64imafdchv_zfh_zba_zbb_zbc_zbs --priv=msu --misaligned --varch=vlen:256,elen:64`

I am running a test with vectors, from disassembly :
`ffffffcd000bec6c:	47dce92f          	.word	0x47dce92f`

expecting spike to take illegal exception but spike is taking store access fault:
```
core   0: 0xffffffcd000bec6c (0x47dce92f) vamoorei32.v v18, (s9), v29, v18
core   0: 0 0xffffffcd000bec6c (0x47dce92f) c8_vstart 0x0000000000000007 e64 m2 l8
core   0: exception trap_store_access_fault, epc 0xffffffcd000bec6c
core   0:           tval 0xffffffce1f066c57
core   0: >>>>  mac_trap
```

According to [vector-amo-extension-zvamo](https://github.com/riscv/riscv-v-spec/blob/master/v-amo.adoc#vector-amo-extension-zvamo):

> The vector AMO instructions are being removed from the standard vector extensions under review at this time. The encoding below will be changed as it collides with scalar subword atomic encoding, but a new encoding is not currently available. The vector AMO instructions will be added as an extension at a later date.

**Comment by aswaterman** [comment]
Executing an opcode that doesn't correspond to a standard instruction is reserved.  Reserved behavior isn't guaranteed to raise an illegal-instruction exception.  It could, for example, result in custom behavior, as is the case here.  There is no bug.

Sometime in the future, probably when the subword atomics are proposed, we will remove these instructions.
