### ISSUE TITLE
Softfloat types conflict with arm_neon.h types

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [riscv/riscv-isa-sim#1349]
The soft float types `float16_t` `float32_t` `float64_t` and `float128_t` have a definition incompatible with the one in the ARM specified arm_neon.h.

While spike itself does not end up including that header, any tool that would end up including spike alongside that ARM header will get some rather "amusing" compilation errors on ARM.

I have fallen victim to one such example which includes SDL.h to make a GUI to a simulator.

It seems to me that prefixing the name of the types in spike would avoid such conflict, I could write up a PR if that would be acceptable. (Some compat #define could be included to allow code relying on the old types to keep compiling, if need be)

**Comment by aswaterman** [comment]
My immediate reaction is that this isn't really a Spike problem, and the workaround you described at https://github.com/ucb-bar/berkeley-softfloat-3/issues/12#issuecomment-1534234747 is acceptable.  But others may disagree with my take.
