### ISSUE TITLE
Zfa: fround vs froundnx

### ISSUE THREAD

**Issue by aamartin0000** [riscv/riscv-isa-sim#1351]
In Ch.25.3 of unpriv, FROUNDNX is defined as the same as FROUND, except that it sets NX if the input differs from the rounded result (and is not NaN).

In the Spike code, both of these instructions call softfloat/f*_roundToInt, while the "exact" operand is true for fround but false for froundnx.  Setting NX is done under some conditions only if the "exact" operand is true.  This appears to conflict with the definition in unpriv.

Am I understanding this incorrectly?  If not, is unpriv correct, or is Spike?

**Comment by aswaterman** [comment]
The spec is unambiguously authoritative in this case.  I'm guessing there was a misunderstanding of the meaning of the `exact` argument to SoftFloat's `roundToInt` routines.  I agree it should be inverted at the call sites.

cc @ptomsich - can you add this to the list of Zfa issues that need to be resolved.

**Comment by ptomsich** [comment]
I'll have to check the SAIL code as well, as I seem to have read "NX" as "_not_ exact".

**Comment by aamartin0000** [comment]
Is this list available somewhere?  I am implementing Zfa in hardware, and need my counterpart to have the correct code in his (Spike-based) verification framework.

**Comment by aswaterman** [comment]
@aamartin0000 the “list” is this GitHub issue tracker. Since the feature was only contributed a few weeks ago, you’ll only need to scan back through a handful of issues to find all of the relevant ones.

**Comment by aswaterman** [comment]
@aamartin0000 I believe just #1312 and #1327, which @ptomsich will presumably handle sometime soon.

**Comment by aamartin0000** [comment]
Ok, thanks.  My verif counterpart told me of another discrepancy, with fleq/fltq.  I'll open a new issue for that.

**Comment by aswaterman** [comment]
Cool.  It takes a village...
