### ISSUE TITLE
Zfa: fleq/fltq should set NV flag if source is SNaN

### ISSUE THREAD

**Issue by aamartin0000** [riscv/riscv-isa-sim#1355]
According to unpriv, the difference between fle/flt and fleq/fltq is that the "q" versions defined in Zfa do not set NV if the source is QNaN, but should set NV if the source is SNaN.  However, the Spike code fleq_*.h/fltq_*.h does not invoke "set_fp_exceptions", meaning SNaN won't set NV.

**Comment by aswaterman** [comment]
Thanks for pointing this one out, @aamartin0000.
