### ISSUE TITLE
For vector instructions，does spike support overwriting inactive elements with 1s? If so, how can I active it?

### ISSUE THREAD

**Issue by linuohai** [riscv/riscv-isa-sim#1358]
For vector instructions，when a set is marked agnostic, the corresponding set of destination elements in any vector destination operand can either retain the value they previously held, or are overwritten with 1s. I see the default option is to retain the valve, I wonder if overwriting with 1s is supported?

**Comment by aswaterman** [comment]
That feature is not currently provided.  Note that providing it in a useful way for comparing against other microarchitectures is not straightforward.  For example, some microarchitectures with register renaming will fill 1s up to the next VLEN boundary, but will leave any remaining vector registers within the vector register group undisturbed.  Others might fill with 1s all the way to the end.
