### ISSUE TITLE
Wrong AMOXXX.D memory result for RV64.

### ISSUE THREAD

**Issue by matszpk** [riscv/riscv-isa-sim#1360]
I found unexpected and erroneous behaviour of AMO64 (atomic memory operations) if some conditions satisfied.
In details: these instructions store wrong result to memory if 31-bit of result is set. Then all higher 32-bits are bits are sets.
Example: `amoxor.d x5, x23, (x18)` store incorrect result to memory if: x5=0xda04520b33223a11, x23=0xc05a0b3fddac2601 then store value 0xffffffffee8e1c10 to memory address in x18. These bug is working for all AMOADD.D, AMOAND.D, AMOOR.D
and maybe of rest of AMO64 instructions.
I am using SPIKE 1.1.0 under 64-bit (AMD64) Linux (Arch Linux).

**Comment by aswaterman** [comment]
I do not observe the same phenomenon when trying a similar case (with bit 31 set).  Please provide instructions to reproduce on HEAD of master.

**Comment by matszpk** [comment]
I found bug in my program that 'produces' that results (wrong type casting). After quick fix: bug doesn't exists.

**Comment by aswaterman** [comment]
Thank you for reporting back!
