### ISSUE TITLE
dret doesn't handle VS/VU modes

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-sim#1365]
The `dcsr.v` bit is described by the debug spec:

> Extends the prv field with the virtualization mode the hart was operating in when Debug Mode was entered. The encoding is described in Table 4.6. A debugger can change this value to change the hart’s virtualization mode when exiting Debug Mode.

The [`dret` implementation](https://github.com/riscv-software-src/riscv-isa-sim/blob/23bc4cd63a1a644566a4fc4e51d75377353df968/riscv/insns/dret.h) in Spike does not look at this bit, or call `set_virt()`, so won't properly return to VS  or VU mode.

I have not looked, but I suspect entry into Debug Mode has a similar problem (failing to set `dcsr.v` appropriately).

cc @timsifive

**Comment by aswaterman** [comment]
I can take a stab at this.
