### ISSUE TITLE
cm.mva01s/cm.mvsa01 disassemble

### ISSUE THREAD

**Issue by alextxia13** [riscv/riscv-isa-sim#1370]
I have seen cm.mva01s/cm.mvsa01 disassembling code is
` DISASM_INSN("cm.mva01s", cm_mva01s, 0, {rvc_rs1s, &rvc_rs2s}); `
In the Zc spike：
xreg1 = {sreg1[2:1]>0,sreg1[2:1]==0,sreg1[2:0]};
xreg2 = {sreg2[2:1]>0,sreg2[2:1]==0,sreg2[2:0]};
From my understanding，the sreg1 & sreg2 for this instruction are not the same as rvc_rs1s and rvc_rs2s, it is a little confused when the spike print the instruction.

**Comment by aswaterman** [comment]
cc @liweiwei90

**Comment by liweiwei90** [comment]
Yes, it's a bug. Two macros (RVC_R1S and RVC_R2S) are used to get its register index for these two instruction.

**Comment by aswaterman** [comment]
Thanks, y'all!
