### ISSUE TITLE
Setting vtype with fractional LMUL and SEW

### ISSUE THREAD

**Issue by weiern1997** [riscv/riscv-isa-sim#1371]
W.r.t V vector extension, setting a fractional LMUL should "support SEW settings between SEWMIN and LMUL *ELEN, inclusive." This does not describe the behaviour for SEW > LMUL*ELEN, for example. when setting LMUL as mf8 (1/8), attempting to set an SEW of 16/32/64 all set the VIL bit. Is this intended behaviour?

**Comment by aswaterman** [comment]
The V spec is carefully written around this and related constraints. Spike implements a valid behavior, but not the only one.
