### ISSUE TITLE
Debugging With Gdb: warning: rot13-64 has a LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by WajahatRiaz** [riscv/riscv-isa-sim#1396]
I'm using the test program and files provided in the GitHub repository. I'm getting the following error: 

`/home/wajahatriaz/RISCV64/riscv64-unknown-elf-toolchain/riscv/bin/../lib/gcc/riscv64-unknown-elf/12.2.0/../../../../riscv64-unknown-elf/bin/ld: warning: rot13-64 has a LOAD segment with RWX permissions
`
<br>The spike.lds file is given below:
```
OUTPUT_ARCH( "riscv" )

SECTIONS
{
  . = 0x10110000;
  .text : { *(.text) }
  .data : { *(.data) }
}
```
<br>The commands being used are as follow: 
```
$ riscv64-unknown-elf-gcc -g -Og -o rot13-64.o -c rot13.c
$ riscv64-unknown-elf-gcc -g -Og -T spike.lds -nostartfiles -o rot13-64 rot13-64.o
```
<br>Kindly look into the **README.md** file in the repository and please let me know if any changes are required. Furthermore, can you please point me to proper documentation for  **riscv-isa-sim** (if any).

**Comment by WajahatRiaz** [comment]
Not sure if anyone is interested in this issue.

**Comment by WajahatRiaz** [comment]
@aswaterman do you have any idea about this?

**Comment by aswaterman** [comment]
Recent versions of binutils issue warnings if executable segments have write permissions.  This is to reduce the likelihood of security vulnerabilities in application code.

The message you quoted isn't an error; it is a warning.  In this context, you can safely ignore it.
