### ISSUE TITLE
vs stage implicit memory access denied by PMP should cause a guest page fault or acess fault

### ISSUE THREAD

**Issue by GuoShibo-cn** [riscv/riscv-isa-sim#1397]
According to Hypervisor Extension, Version 1.0
![img_v2_f877b96b-d2da-4549-b38a-b55065b295eg](https://github.com/riscv-software-src/riscv-isa-sim/assets/117092168/2c851cd7-8699-4492-aec1-b453a5b6e092)
Implicit memory access during first-stage(VS-stage) address translation, may arise guest page fault , what if the fault is caused by PMP deny? Should it rise an access fault or guest page fault. Recently Spike rise access fault.
  
![59d4427c-f543-4970-ac91-8c1f09397e64](https://github.com/riscv-software-src/riscv-isa-sim/assets/117092168/d98e984e-9274-4e47-9dea-88ead0835ed4)
![ff85c036-93e5-4f8f-b767-ef84a0a3630d](https://github.com/riscv-software-src/riscv-isa-sim/assets/117092168/43494153-eb45-4beb-aab5-b3ee54ee91a1)

**Comment by scottj97** [comment]
PMP errors always throw access faults, never page faults. There's no such thing as a guest access fault.

**Comment by GuoShibo-cn** [comment]
Get it. Thanks !
