### ISSUE TITLE
Allow overriding `mem_t`

### ISSUE THREAD

**Issue by michalt** [riscv/riscv-isa-sim#1408]
Hi! We'd like to be able to inject custom implementation of `mem_t` (that contains just a single `char*` for its memory) when building `sim_t`. Currently this is not possible since the methods of `mem_t` are not `virtual`, and the implementation of `mem_t` is sparse (splits things into page-sized allocations and stores them in `std::map`). 

There are a few options how this could be supported:

1. Change `mem_t` to support both the current sparse version of memory as well as just a `char*` (through something like `std::variant` or a manual tag).
2. Change `mem_t` to be an abstract class, where its current implementation would move to its own class `sparse_mem_t` (similarly to what #1342 does).
3. Make the methods of `mem_t` virtual. Currently only `contents()` would really need to be virtual.

Let me know what you think about it and if you have any better ideas! Thanks in advance! 😃

**Comment by michalt** [comment]
@aswaterman Any opinions/suggestions? I'd be happy to send a PR! 😃

**Comment by aswaterman** [comment]
@jerryz123 you were looking into doing something along these lines recently, right? What did you end up doing?

**Comment by jerryz123** [comment]
We didn't end up needing this feature.

I think approach 3) is the best, make the interfaces of `mem_t` virtual such that code which links to `libriscv` can provide their own implementation to pass to `sim_t`.

**Comment by aswaterman** [comment]
If that does actually suffice for @michalt’s use case, I’m fine with it. @michalt care to make a PR? If you prefer, we can hold off on merging it until you’re sure it’s sufficient.

**Comment by michalt** [comment]
Sounds good, I'll test things on my end and send you a PR. Thanks!

**Comment by michalt** [comment]
Thanks for help everyone! 😄
