### ISSUE TITLE
Vector Mask instructions non zero vstart

### ISSUE THREAD

**Issue by ajayvreddy** [riscv/riscv-isa-sim#1431]
Hi,

I wanted to get clarification of the behavior of vector mask instructions when vstart is non-zero.

e.g. vcpop.m, the spec mentions:
`Traps on vcpop.m are always reported with a vstart of 0. The vcpop.m instruction will raise an illegal instruction exception if vstart is non-zero.`

Does it mean that on an illegal instruction exception, vstart should be written with value 0.
if yes, should it also set MSTATUS.VS to dirty because VStart was written.

**Comment by aswaterman** [comment]
No, vstart shouldn't be written in this case.  And, as you said, vstart being changed should correspond to mstatus.VS being set to Dirty.

**Comment by jrahmeh** [comment]
So illegal instruction traps should leave vstart as is, and all other traps should clear it?

**Comment by aswaterman** [comment]
I don’t think that follows…?

**Comment by jrahmeh** [comment]
"traps on vcpop.m are always reported with a vstart of 0" says that that vstart should be cleared on traps?  What am I missing?

**Comment by aswaterman** [comment]
It’s an overly literal parsing of the spec. I think you know what it’s actually saying

**Comment by jrahmeh** [comment]
I am not being pedantic, our team cannot agree on how to parse this.  One person suggested that what the spec is saying is: traps caused by vstart being non-zero should leave vstart alone.  All other traps should clear vstart.  Is that a reasonable reading of the spec?

**Comment by aswaterman** [comment]
In general, instructions that result in illegal-instruction exceptions shouldn’t be modifying any state. The spec’s comment about traps being reported with a vstart of 0 is really about interruptibility.
