### ISSUE TITLE
defining arch corrupted the behaviour of spike.

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [riscv/riscv-isa-sim#1432]
I have a `coremark.baremetal.riscv` as an executable for `rv64gc`.
I run this in spike by two different command with spike below.
First one:	`spike -l --log-commits --log=spike_trace2.log  coremark.bare.riscv`
Second:	` spike -l --log-commits --isa=rv64gc --log=spike_trace.log  coremark.bare.riscv`
the command with `--isa=rv64gc` excepting the `start_time` part while reading the `cycle` csr. the log is below.
```
core   0: 0x0000000080001846 (0x0000efa9) c.bnez  a5, pc + 90
core   0: 3 0x0000000080001846 (0xefa9)
core   0: 0x00000000800018a0 (0x21a010ef) jal     pc + 0x121a
core   0: 3 0x00000000800018a0 (0x21a010ef) x1  0x00000000800018a4
core   0: >>>>  start_time
core   0: 0x0000000080002aba (0xc00027f3) csrr    a5, cycle
core   0: exception trap_illegal_instruction, epc 0x0000000080002aba
core   0:           tval 0x00000000c00027f3
core   0: 0x00000000800000e4 (0x00004197) auipc   gp, 0x4
core   0: 3 0x00000000800000e4 (0x00004197) x3  0x00000000800040e4
core   0: 0x00000000800000e8 (0x26c18193) addi    gp, gp, 620
core   0: 3 0x00000000800000e8 (0x26c18193) x3  0x0000000080004350
```
The other one has no exception. 
Is there a point that I missed?
Could you help me to understand this?

**Comment by widlarizer** [comment]
This is duplicate with #1472 so I suggest you close this

**Comment by omerguzelelectronicguy** [comment]
oh I forget this issue that I opened already sorry for that.
