### ISSUE TITLE
the print log of spike

### ISSUE THREAD

**Issue by hyperion009** [riscv/riscv-isa-sim#1433]
Hi All
here is a snapshot of  snippet code :
![1691074725337](https://github.com/riscv-software-src/riscv-isa-sim/assets/30075118/a2af4025-761b-4bc7-a248-1da9f61dae93)
here is a log of spike executing a snippet above:
![1691074863597](https://github.com/riscv-software-src/riscv-isa-sim/assets/30075118/0bfbc7ea-b168-411c-abfd-8432db368eb5)
I am wandering about "beq t0, t1, c" circled by read.  why did the spike print "pc+4"? c=pc(8)+4, right?

thanks
L.Y.F

**Comment by aswaterman** [comment]
Different styles, same information.
