### ISSUE TITLE
use SRET enter HS-mode, sstatus.SPIE sets 0

### ISSUE THREAD

**Issue by heiyuen1999** [riscv/riscv-isa-sim#1437]
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/110437689/85100a8c-6c4b-460b-8936-d80e704eb221)
This test program attempts to enter VS mode using SRET.According to the spec, sstatus.SPIE should be set to 1 after SRET.
And why is sepc cleared to 0?
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/110437689/35b52bfe-f23e-482a-bdef-58071723ea99)
The results of the spike run are as follows：
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/110437689/2e3c2d60-a51b-481a-98a4-182c0498fa17)
```
//my internal lib
#<am.h>
#<klib.h>
#<klib-macros.h>

void sret_test(); //here is the test

void success(){
printf("test pass\n");
asm("li a0,0\n");
asm(".word 0x0000006b\n");
}

int main(){
sret_test(); //here is the test caller
return 0;
}





#define CSR_SSTATUS 0x100
#define CSR_SEPC 0x141
#define CSR_HSTATUS 0x600
#define SSTATUS_SPP 0x00000100
#define HSTATUS_SPV (1ULL << 7)
#define HSTATUS_SPVP (1ULL << 8)

pmp_init:
li a1,0xfffffffff
csrw pmpaddr0,a1
li a1,0xef
csrw pmpcfg0,a1

hstatus_init:
li a2，(HSTATUS_SPV | HSTATUS_SPVP )
csrs CSR_HSTATUS,a2 
li a2，SSTATUS_SPP
csrs CSR_SSTATUS,a2 

sepc_init:
la a1 ,1f
csrw CSR_SEPC ,a1
sret # jump to VS mode
#=================
#now run in VS mode
#=================
1:
VS_begin:
nop
nop
nop
nop
nop
j success

```
Thanks

**Comment by scottj97** [comment]
Are you going to make me type all that in to recreate your problem? Why not paste the code as text instead of image? Help us help you.

**Comment by heiyuen1999** [comment]
> Are you going to make me type all that in to recreate your problem? Why not paste the code as text instead of image? Help us help you.

Sorry.I've pasted the code as text.

**Comment by scottj97** [comment]
I suspect what's happening here is that the interactive Spike debugger is seeing `vsstatus` when you ask for `sstatus`, since the core is in VS-mode. The actual `sstatus` does indeed have SPIE=1, which you can see by asking for `mstatus` instead. (`sstatus` is simply a masked version of `mstatus`).

Is this desirable behavior? Probably not...I think the interactive debugger should act as God and report all architectural CSRs as they are, instead of the virtualized versions when in VS-mode or VU-mode.

But I don't think there's any bug in Spike's execution of the target program. The only issue is with the interactive debugger reporting confusing values.

**Comment by aswaterman** [comment]
I think you’re right, @scottj97. OTOH, we do benefit from being able to use the interactive mode to access memory under the current context’s address-translation regime, so we probably don’t want to make _all_ interactive commands behave as though they’re in god mode.

**Comment by heiyuen1999** [comment]
> I think you’re right, @scottj97. OTOH, we do benefit from being able to use the interactive mode to access memory under the current context’s address-translation regime, so we probably don’t want to make _all_ interactive commands behave as though they’re in god mode.

Okay. I see. Thanks for the answer.

**Comment by heiyuen1999** [comment]
> I think you’re right, @scottj97. OTOH, we do benefit from being able to use the interactive mode to access memory under the current context’s address-translation regime, so we probably don’t want to make _all_ interactive commands behave as though they’re in god mode.

Okay. I see. Thanks for the answer.
