### ISSUE TITLE
vector crypto insn vaeskf2.vi seems unmatch spec

### ISSUE THREAD

**Issue by GuoShibo-cn** [riscv/riscv-isa-sim#1440]
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/117092168/c2ee1602-1e6d-4e73-81d9-61b3526fd16c)
According to spike vaeskf2_vi function implementation, use "(round >> 1) - 1" to look up round constants, However, spec use 
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/117092168/6373efb5-fd77-44f2-b2da-ae34f5fd3e00)
(round >> 1) ,  could it be a slip of the pen?

**Comment by aswaterman** [comment]
@kdockser any insight?

**Comment by aamartin0000** [comment]
This was discussed and resolved here:
https://github.com/riscv/riscv-crypto/issues/336

Not sure if it's been updated everywhere.

**Comment by kdockser** [comment]
The pseudocode in the latest version ([Vector Crypto Specification 1.0.0-rc2](https://github.com/riscv/riscv-crypto/releases/download/v/riscv-crypto-spec-vector.pdf)) has the correct equation
`aes_subword_fwd(aes_rotword(CurrentRoundKey[3])) XOR aes_decode_rcon((rnd>>1) - 1) XOR RoundKeyB[0];`

**Comment by aswaterman** [comment]
So I think Spike is doing the right thing already.  Right, @GuoShibo-cn?

**Comment by GuoShibo-cn** [comment]
Yes, Thanks, didn't realize spec change, spike is doing the right thing! It helps a lot.
