### ISSUE TITLE
How to use Spike with DPI in SystemVerilog?

### ISSUE THREAD

**Issue by omerkarslioglu** [riscv/riscv-isa-sim#1442]
Hello!

I want to use Spike Core functions in my SystemVerilog testbench with DPI (to compare just L1 data cache write data outputs between Spike and my core). Is it possible? If yes what should I do?

Thanks,
Omer

**Comment by scottj97** [comment]
It should work the same as linking any other C++ code via DPI.

You need a SystemVerilog DPI help forum, not the Spike issue tracker.

**Comment by omerkarslioglu** [comment]
Thanks for the answer.

Essentially I was curius about which should I examine directory or files of Spike to integrate Spike in my testbench?
