### ISSUE TITLE
question of riscv/insns/vmv_s_x.h code

### ISSUE THREAD

**Issue by EventScheduler** [riscv/riscv-isa-sim#1444]
I don't think vmv.s.x should update vd[0] element when vstart=1 and vl =2, but code in riscv/insns/vmv_s_x.h did, is it correct?

**Comment by aswaterman** [comment]
It’s a fair question. This instruction would never set vstart=1, even if interrupted. Therefore, trapping is a legal option (but is not required). I would say it is UNSPECIFIED, so writing vd[0], trapping, or NOP would all be reasonable choices. But this is just an opinion.

**Comment by EventScheduler** [comment]
I can build this scenario with the following code:
li t0, 2
vsetvli t1, t0, e8,m1,ta,ma
li   t0,1
csrw   vstart,t0
vmv.s.x v1, s0

**Comment by aswaterman** [comment]
Thank you for the test case. At this point, I think it is an ISA question, not a Spike question.

**Comment by EventScheduler** [comment]
Can't agree with you more, aswaterman.
Thank you a lot for your kind comments. Have a good day!

**Comment by aswaterman** [comment]
You as well!
