### ISSUE TITLE
How to interrupt CPU under WFI 

### ISSUE THREAD

**Issue by rahul-neubla** [riscv/riscv-isa-sim#1460]
Hi,

I am using Spike for CPU simulation running along with my Coprocessor simulator. To sync between CPU and coprocessor, I want to simulate interrupt from coprocessor to CPU, with CPU waiting in WFI. Could I simply rely on updating `in_wfi` in `processor.cc` or is there some elegant way to do this. Any help/pointers would be very useful :)

Thanks,
Rahul

**Comment by jerryz123** [comment]
Updating `in_wfi` is insufficient, as a processor can take an interrupt while not in a `wfi` state. 
Updating `state.mip` is the correct approach. You can take a look at how the CLINT/PLIC raise MIP in clint.cc and plic.cc for examples.

There is also an example of how to use the Spike C++ API for co-simulation here: https://github.com/ucb-bar/testchipip/blob/master/src/main/resources/testchipip/csrc/cospike_impl.cc

**Comment by rahul-neubla** [comment]
> Updating `in_wfi` is insufficient, as a processor can take an interrupt while not in a `wfi` state. Updating `state.mip` is the correct approach. You can take a look at how the CLINT/PLIC raise MIP in clint.cc and plic.cc for examples.
> 
> There is also an example of how to use the Spike C++ API for co-simulation here: https://github.com/ucb-bar/testchipip/blob/master/src/main/resources/testchipip/csrc/cospike_impl.cc

Thanks, thats quite helpful
