### ISSUE TITLE
Need clarification regarding program buffer execution.

### ISSUE THREAD

**Issue by abhi-valtrix** [riscv/riscv-isa-sim#1462]
I am unable to see any change post the program buffer execution. Am I missing something here ? Appreciate any help :)

opcode :	00468693         addi   a3,a3,4

openocd commands : 

> poll off
> reg 13              
a3 (/32): 0x00000000

> riscv dmi_write 0x20    0x00468693                    - writing progbuf0 with the opcode of the addi instruction.
> riscv dmi_write 0x21    0x00468693                    - writing progbuf1 with the opcode of the addi instruction. 
> reg 13                         
a3 (/32): 0x00000000

> riscv dmi_write  0x17 0x40000                         -  only postexec bit is 1
> reg 13                        
a3 (/32): 0x00000000

> riscv dmi_read 0x16
0x2000002

**Comment by timsifive** [comment]
OpenOCD will cache the value of all GPRs. I don't think there's code to realize that dmi_write can change their values.

**Comment by abhi-valtrix** [comment]
Thanks @timsifive , was able to bypass the cache using the force option. Closing the issue.

> reg 13 
a3 (/32): 0x00000000

> reg 13 force
a3 (/32): 0x00000008

Also can use the abstract access register command to get the correct value.

> riscv dmi_write  0x17 0x22100d
> riscv dmi_read 0x4
0x8
