### ISSUE TITLE
Misleading behavior of exception type for writing several counters under V=1

### ISSUE THREAD

**Issue by viktoryou** [riscv/riscv-isa-sim#1466]
According to the spec (Priv. chapter 8.6.1): 
> When V=1, a virtual instruction exception (code 22) is normally raised instead of an illegal instruction exception if the attempted instruction is HS-qualified but is prevented from executing when V=1 either due to insufficient privilege or because the instruction is expressly disabled by a supervisor or hypervisor CSR such as scounteren or hcounteren.

it seems virtual instruction exception would be raised in two scenarios, the latter one can be found as:
> Specifically, a virtual instruction exception is raised for the following cases: in VS-mode, attempts to access a non-high-half counter CSR when the corresponding bit in hcounteren is 0 and the same bit in mcounteren is 1;

To my understanding, when writing some URO counters in VS mode, meeting the condition of  the corresponding bit in hcounteren is 0 and the same bit in mcounteren is 1, the exception type should be a virtual instruction exception, while the behavior of spike seems to output an illegal exception(https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/csrs.cc#L42). I am wondering if there is a spike bug or anything needed to clarify further in the specification.

**Comment by aswaterman** [comment]
In general, if a given instruction would raise an illegal-instruction exception when V=0, it will also raise an illegal-instruction exception when V=1. (Virtual-instruction exceptions are raised only when the instruction is emulable by the hypervisor.) Writing a read-only CSR will raise an illegal-instruction exception in V=0, so it’ll also do so when V=1. The fact these CSRs are counters is a red herring. The snippet you quoted about counters applies to reads only. (If you parse the spec carefully, you’ll see this isn’t actually ambiguous, though it is true it requires absorbing the entirety of the rule set.)
