### ISSUE TITLE
How to generate tests for RV64D and RV64F using riscv-ctg?

### ISSUE THREAD

**Issue by riscvzbs** [riscv/riscv-isa-sim#1480]
When I use 'riscv_ctg -v debug -d ./tests/ -r -cf ./sample_cgfs/dataset.cgf -cf ./sample_cgfs/rv64i.cgf -bi rv64i -p2,' I can generate tests for RV64I. However, I couldn't find the provided rv64d.cgf and rv64f.cgf. Now I want to generate tests for D and F extensions. How can I do that? Looking forward to your guidance. Thank you very much.

**Comment by jerryz123** [comment]
This question should be directed to the riscv-ctg repository.
