### ISSUE TITLE
How to run cm.jalt instruction of Zcmt Extension in Embench-iot programs by Spike?

### ISSUE THREAD

**Issue by gakubochama** [riscv/riscv-isa-sim#1485]
I tried to run cm.jalt instruction of Zcmt Extension in Embench-iot programs by Spike, but I can't.

command↓
`spike --isa=rv32ima_zicsr_zca_zcb_zcmp_zcmt -d cubic`
(cubic is elf file)

the console output↓
```
core   0: 0x8000003e (0x00004f81) c.li    t6, 0
(spike) 
core   0: 0x80000040 (0x80012137) lui     sp, 0x80012
(spike) 
core   0: 0x80000044 (0x0000a1a6) cm.jalt 105
core   0: exception trap_instruction_access_fault, epc 0x80000044
core   0:           tval 0x000001a4
(spike) 
core   0: exception trap_instruction_access_fault, epc 0x00000000
core   0:           tval 0x00000000
(spike) 
core   0: exception trap_instruction_access_fault, epc 0x00000000
core   0:           tval 0x00000000
```

Tell me how to solve this problem.

And [Zc's specification](https://github.com/riscv/riscv-code-size-reduction/tree/main) says
> Table jump uses a 256-entry XLEN wide table in instruction memory to contain function addresses.
The table must be a minimum of 64-byte aligned.

so where is the address of table in instruction memory??

I could run Zca,Zcb,Zcmp instructions by Spike without any problems.

**Comment by aswaterman** [comment]
The jvt CSR has not been initialized to a value that points to a useful table. Note that the exception address 0x1a4 is equal to the cm.jalt target of 105 times the table entry size of 4, meaning the jvt CSR is 0.

This isn’t a Spike issue; you should consult the Zcmt spec and your toolchain documentation for additional info.

**Comment by jnk0le** [comment]
>so where is the address of table in instruction memory??

Usually, the table should be generated by compiler + some linker symbols
You could also manually put function pointers there

**Comment by gakubochama** [comment]
@jnk0le 
Ok,manually...
But, why wasn't the table created automatically by the compiler, perhaps because the start function, which calls the main function, was written directly in assembly language?

↓ like this
```asm=
    .section .text.init
    .globl _start
_start:
    nop
    li x1, 0
    li x2, 0
    li x3, 0
    li x4, 0
    li x5, 0
    li x6, 0
    li x7, 0
    li x8, 0
    li x9, 0
    li x10, 0
    li x11, 0
    li x12, 0
    li x13, 0
    li x14, 0
    li x15, 0
    li x16, 0
    li x17, 0
    li x18, 0
    li x19, 0
    li x20, 0
    li x21, 0
    li x22, 0
    li x23, 0
    li x24, 0
    li x25, 0
    li x26, 0
    li x27, 0
    li x28, 0
    li x29, 0
    li x30, 0
    li x31, 0

    # set the stack pointer 64 KiB
    li sp, 0x80100000

    # set the jvt csr
    li t0, 0x80010000
    csrrw x0, 0x0017, t0
    li t0, 0

    jal main

    # shutdown
    li t0, 1
    sw t0, tohost, t1
1:  j 1b
```
