### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by wplf** [riscv/riscv-isa-sim#1492]
can not find the "statx"
``` bash
make: Circular libcustomext.so <- libcustomext.so dependency dropped.
make: Circular libsoftfloat.so <- libsoftfloat.so dependency dropped.
g++ -L. -Wl,--export-dynamic -L/lib64  -Wl,-rpath,/data/lijinliang/bin/riscv-toolchain/lib  -o spike spike.o  libspike_main.a  libriscv.a  libdisasm.a  libsoftfloat.a  libfesvr.a  libfdt.a -lpthread -ldl -lpthread   
libfesvr.a(syscall.o): In function `syscall_t::sys_statx(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)':
/data/lijinliang/bin/riscv-isa-sim-dummy-tag-for-ci-storage/build/../fesvr/syscall.cc:315: undefined reference to `statx'
collect2: error: ld returned 1 exit status
Makefile:349: recipe for target 'spike' failed
make: *** [spike] Error 1
```

**Comment by aswaterman** [comment]
Unfortunately, it seems you are on a platform where our configure-time detection of whether `statx` is available is broken.  Your platform apparently defines `struct statx` and has a function prototype for `statx` but doesn't supply the implementation.  The relevant detection code is here, and you could try rewriting it to work for your platform and contributing a PR.  https://github.com/riscv-software-src/riscv-isa-sim/blob/eeef09ebb894c3bb7e42b7b47aae98792b8eef79/fesvr/fesvr.ac#L3-L6

**Comment by wplf** [comment]
Thank you for response.
Sorry, rewriting is kind of difficult for me :(
By the way, can we release some binary code for `riscv-isa-sim`  just like `riscv-gnu-toolchain`?

**Comment by aswaterman** [comment]
Unfortunately, we don't have the resources to support binary releases.  You might consider using a VM to run an OS that's capable of building these projects natively.

**Comment by wplf** [comment]
Thank you for response, I will try it :)
