### ISSUE TITLE
For some EXT_ZVBB instruction, not expected exception happen.

### ISSUE THREAD

**Issue by alextxia13** [riscv/riscv-isa-sim#1505]
Hi, vwsll_vx & vwsll_vi instructions use VI_ZVK_VX_WIDING_ULOOP & VI_ZVK_VI_WIDING_ULOOP  macros. I noticed that VI_CHECK_DSS(true) means rs1 in the instruction is vs, and will check rs1 overlap and require align for rs1. But for vmsll_vx & vwsll_vi, I think these instruction rs1 is not vector register, and they do not need to check align or overlap for execution.
Is there anything wrong here or I have some misunderstanding about the spike.

Thanks.

**Comment by aswaterman** [comment]
Indeed.  I made a PR to fix this bug.
