### ISSUE TITLE
fmvp.d.x issue when RS1 sigh-extended with 1

### ISSUE THREAD

**Issue by Madman-Hugo** [riscv/riscv-isa-sim#1507]
here is the fmvp.d.x code：
> require_rv32;
require_extension('D');
require_extension(EXT_ZFA);
require_fp;
ui64_f64 ui;
ui.ui = ((uint64_t)RS2) << 32;
ui.ui |= RS1;
WRITE_FRD_D(f64(ui.ui));

If we use **ui.ui |= RS1** when RS1 high bits is sigh-extended with 1, the result RD will get all 1s for high 32bits

**Comment by aswaterman** [comment]
Yes, this looks like a bug.
