### ISSUE TITLE
The BASE field of mtvec appears to lack alignment checking for 4-byte alignment.

### ISSUE THREAD

**Issue by youzi27** [riscv/riscv-isa-sim#1518]
When I attempted to write a value to _mtvec_, the BASE field of _mtvec_ does not check for **4-byte alignment.** In other words, the lowest bit of the BASE field can be binary 1.

Privilege Specification 3.1.7 states: 

> The value in the BASE field must always be aligned on a 4-byte boundary.

How to reproduce:
```
...
addi    s11, s11, -64
ori x11, x11, 0xff
csrw mtvec, x11 
...
```
The log in Spike displays:
```
core   0: 0x0000000080000044 (0xfc0d8d93) addi    s11, s11, -64
(spike) 
core   0: 0x0000000080000048 (0x0ffded93) ori     s11, s11, 255
(spike) 
core   0: 0x000000008000004c (0x305d9073) csrw    mtvec, s11
(spike) reg 0 mtvec
0x000000008005f0fd
```
If I am mistaken in any way, I appreciate any corrections. Thank you.

**Comment by scottj97** [comment]
See explanation in #1519.

**Comment by youzi27** [comment]
The BASE area is MXLEN-2 (from bit 63 to bit 2, where bits 1 to 0 are the MODE field, unrelated to BASE, in 64-bit), not BASE+MODE. The four-byte alignment you mentioned includes the MODE field, right? But BASE and MODE are calculated separately. Besides, MODE can be set to 1 (it's just not supported by default in spike), but according to your method, MODE can only be 0, which is obviously incorrect.
If I have any mistakes, I hope you can point them out.

**Comment by youzi27** [comment]
> See explanation in #1519.

In other words, the mtvec register consists of two completely different functional segments, which are not directly related to each other. When calculating BASE, the MODE bits should not be considered. That is, BASE is the higher part of mtvec (bits 2-63, in a 64-bit system).
