### ISSUE TITLE
[Bug Report] Exception Priority Error for Ext.Code 12/1 and 0

### ISSUE THREAD

**Issue by youzi27** [riscv/riscv-isa-sim#1528]
### Description
**Type of issue:** bug report

**Impact:** unknown

**Development Phase:** request

**Detailed Description**
Error Manifestation: In U mode, the priorities for **Instruction page fault** and **Instruction address misaligned** are incorrectly implemented. In M mode, the priorities for **Instruction access fault** and **Instruction address misaligned** are incorrectly implemented.

When attempting to jump to an illegal target address and the target address of the jump instruction is misaligned, it should prioritize displaying as 'Instruction Page Fault' exception in mcause(as shown in the RISC-V Privileged Specification diagram below). However, in practice, the mcause register incorrectly displays an "Instruction Address Misaligned" exception. Note that this issue is of a similar nature to the previous issue #971 , **but** it involves a **different exception priority problem.**
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/62980522/3c4b7dee-fd6d-4871-8c8a-2b44e9eebf82)

### Steps to Reproduce
spike version: 1.1.1-dev
**How to reproduce**

```
...
- # in U/M mode
- ...
- li x15,0x80000000fff0000 # or li x15,0x80000000fff0002 . To demonstrate the simultaneous presence of both exceptions.
- jalr x15
...
```
The results are as follows:
In M mode:
```
- # li x15,0x80000000fff0000
- ...
- core   0: 0x00000000800001c8 (0x000780e7) jalr    a5
- (spike) 
- core   0: exception trap_instruction_access_fault, epc 0x080000000fff0000
- core   0:           tval 0x080000000fff0000
- (spike) reg 0 mcause
- 0x0000000000000001
- ...
```
```
- # li x15,0x80000000fff0002
- ...
- (spike) 
- core   0: 0x00000000800001c8 (0x000780e7) jalr    a5
- core   0: exception trap_instruction_address_misaligned, epc 0x00000000800001c8
- core   0:           tval 0x080000000fff0002
- (spike) reg 0 mcause
- 0x0000000000000000
- ...
```
From the tests described above, it was observed that when the jump address is 0x80000000fff0002, it triggers both **Instruction access fault** and **Instruction address misaligned** exceptions simultaneously, with **Instruction access fault** taking priority for display. **However**, it incorrectly displays **Instruction address misaligned**.

In U mode:

```
- # li x15,0x80000000fff0000
- ...
- (spike) 
- core   0: exception trap_instruction_page_fault, epc 0x080000000fff0000
- core   0:           tval 0x080000000fff0000
- (spike) reg 0 mcause
- 0x000000000000000c
- ...
```

```
- # li x15,0x80000000fff0002
- ...
- (spike) 
- core   0: 0x0000000080000220 (0x000780e7) jalr    a5
- core   0: exception trap_instruction_address_misaligned, epc 0x0000000080000220
- core   0:           tval 0x080000000fff0002
- (spike) reg 0 mcause
- 0x0000000000000000
- ...
```

Testcase:
[test.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/13615466/test.zip)

**Comment by aswaterman** [comment]
Spike is correct, though the reasoning is subtle.  The misaligned trap occurs _on the JALR_.  The fetch of the subsequent instruction has not even begun yet, and so we don't even know that there is a page fault.

The table you quoted describes the priority exceptions caused by a single instruction, but here, there are two instructions involved (first the JALR, then the target), and so any exceptions on the JALR must be processed before any exceptions on the target are processed.

**Comment by youzi27** [comment]
Thank you @aswaterman , your explanation is very accurate. I checked the relevant code in spike, and it matches what you said. Thanks again!

**Comment by aswaterman** [comment]
You’re welcome!
