### ISSUE TITLE
The result of fcvtmod_w_d when frs1 is a negative number with large exponent

### ISSUE THREAD

**Issue by alextxia13** [riscv/riscv-isa-sim#1553]
![1](https://github.com/riscv-software-src/riscv-isa-sim/assets/135207047/2937aff9-f514-4170-89be-d0fa4f45562d)

I met a question when I run zfa_ext instruction fcvtmod_w_d, the input value is a negative number with large exponent as shown in pic. I think the result of calculation is -0 which is ffffffff80000000 but the spike result is 0. As shown in spike, I saw the code that when sign=1, frac = -frac, but it nor works. Please help to take a look. Thanks!
<img width="211" alt="2" src="https://github.com/riscv-software-src/riscv-isa-sim/assets/135207047/aaa95214-73f1-43ab-a85b-1759751c4065">

**Comment by nibrunieAtSi5** [comment]
The expected result for `fcvtmod.w.d` is an integer (32-bit signed integer) not a floating-point. So I don't think we can interpret any result as `-0`. 

`0xea1f7a9391340a41` is a very large (negative) multiple of 2^32 ~2^674, so the integer modulo 2^32 is expected to be zero. I think spike is right in that case (assuming the invalid flag is raised to indicate an input outside the valid range for `fcvt.w.s`).

**Comment by alextxia13** [comment]
Thanks for the reply. But when I run the fcvt.w.d instruction which result is also an integer value not a floating-point with the input value 0xea1f7a9391340a41 and rounding-mode RTZ. The result is 0xffffffff80000000. I think -0 is an available result although it is a 32 bit integer value. 
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/135207047/44d5e3ae-8994-4dca-985c-d56a22f19213)

**Comment by nibrunieAtSi5** [comment]
Beware than in the case of `fcvt.w.d` since there is no modulo, the output is the value which corresponds to invalid inputs:
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/82109999/b950c9a4-936a-4a4a-bdf4-2f526630126c)

So here `0xffffffff80000000` is the sign extension of `-2^31`, not `-0`.

**Comment by alextxia13** [comment]
I got it. Thanks for your help.

**Comment by nibrunieAtSi5** [comment]
> I got it. Thanks for your help.

You are welcome.
