### ISSUE TITLE
how can i set my spike --isa to rv64i from --isa rv32i?

### ISSUE THREAD

**Issue by Vinayakamk** [riscv/riscv-isa-sim#1567]
as you can see spike -l --isa=rv32i ,and the things i have used (make file has this as -march=rv64imafdc -mabi=lp64  ,in terms of 64bit,,)

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/137029135/846e3d1a-1a1a-494e-b046-218e9d4c5848)
i hope the spike default isa is rv32
im very new this.
kindly help how can i set it,sorry by chance if already the same question was posted anytime

**Comment by jerryz123** [comment]
This is a compilation error, not a spike error. Your question would be best directed to whomever owns that software flow.

**Comment by Vinayakamk** [comment]
okay,sure thanks for the reply
