### ISSUE TITLE
Intermittent Instruction Decoding Failure in Spike during Prolonged Nested Exceptions

### ISSUE THREAD

**Issue by youzi27** [riscv/riscv-isa-sim#1568]
**Type of issue:** bug report

**Impact:** not sure

**Development Phase:** request

**Detailed Description:**
While testing nested exceptions in Spike, the simulator initially handles the exceptions correctly. However, with a large number of nested exceptions, Spike encounters an instruction decoding error at the correct program counter (PC), resulting in an illegal instruction exception. This behavior does not occur with the same test set on the Rocket-chip implementation, where the exceptions are handled as expected without any decoding errors.

**Steps to Reproduce:**
1. Run a RISC-V program in Spike that triggers a large number of nested exceptions.
2. Observe the behavior of Spike in handling these exceptions, especially focusing on the instruction decoding process at the correct PC values. (I have constructed a test suite for this scenario in the attachment)

For the provided test suite, Spike can be run with the command until reg 0 s0 80003090 (at this point, a large number of nested exceptions have already occurred). Subsequently, if continued with single-step debugging, an error will occur when the PC reaches 0x8000308a. Note, you cannot directly jump to PC=0x8000308a, as jumping directly would lead to the PC of the first exception handling routine, not after the nesting.

Early in the exception handling, the log for PC=0x8000308a in Spike:
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/62980522/3218c0cb-e766-417c-babe-185204374c2f)
After a large number of nested exceptions, the log for PC=0x8000308a in Spike:
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/62980522/c4852418-828d-4d0c-ba80-fb387b7a02ca)

**Environment:**
- Spike version: 1.1.1-dev

**Additional Information:**
For comparison, I ran the same program on Rocket-chip and found that Rocket-chip can correctly handle all the nested exceptions.

**testcase:**
[testcase.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/13962276/testcase.zip)

**Comment by jerryz123** [comment]
In your test case, saving registers to the stack in `<mmode_exception_handler>` eventually overwrites itself, the PC and the stack stores collide at `0x8000308a`

```
core   0: 0x0000000080003082 (0x0000f1f2) c.sdsp  t3, 224(sp)
(spike) 
core   0: 0x0000000080003084 (0x0000f5f6) c.sdsp  t4, 232(sp)
(spike) mem 0 0x8000308a
0x0000000000000433
(spike) 
core   0: 0x0000000080003086 (0x0000f9fa) c.sdsp  t5, 240(sp)
(spike) mem 0 0x8000308a
0x0000000000000433
(spike) 
core   0: 0x0000000080003088 (0x0000fdfe) c.sdsp  t6, 248(sp)
(spike) mem 0 0x8000308a
0x0000000000000000
(spike) 
core   0: 0x000000008000308a (0x00000000) c.unimp
core   0: exception trap_illegal_instruction, epc 0x000000008000308a
core   0:           tval 0x0000000000000000
```

**Comment by youzi27** [comment]
> In your test case, saving registers to the stack in `<mmode_exception_handler>` eventually overwrites itself, the PC and the stack stores collide at `0x8000308a`
> 
> ```
> core   0: 0x0000000080003082 (0x0000f1f2) c.sdsp  t3, 224(sp)
> (spike) 
> core   0: 0x0000000080003084 (0x0000f5f6) c.sdsp  t4, 232(sp)
> (spike) mem 0 0x8000308a
> 0x0000000000000433
> (spike) 
> core   0: 0x0000000080003086 (0x0000f9fa) c.sdsp  t5, 240(sp)
> (spike) mem 0 0x8000308a
> 0x0000000000000433
> (spike) 
> core   0: 0x0000000080003088 (0x0000fdfe) c.sdsp  t6, 248(sp)
> (spike) mem 0 0x8000308a
> 0x0000000000000000
> (spike) 
> core   0: 0x000000008000308a (0x00000000) c.unimp
> core   0: exception trap_illegal_instruction, epc 0x000000008000308a
> core   0:           tval 0x0000000000000000
> ```

Hi @jerryz123 ! Thank you for the explanation. By the way, what puzzles me is why Rocket can successfully execute the instruction at mem=0x8000308a? Rocket's successful execution is demonstrated by it successfully executing the next instruction **add s0, sp, zero**, which resulted in the modification of the value of s0.

Thank you again for your patient explanation!

**Comment by jerryz123** [comment]
Rocket has a L1 instruction cache. So the execution proceeds correctly on Rocket, with the fetch to 0x8000308a reading the stale data from the L1 ICache.

In RISC-V, synchronization between writes to instruction memory and instruction fetch by the same hart is not guaranteed unless a `fence.i` instruction is executed between the write and the fetch.

**Comment by youzi27** [comment]
> Rocket has a L1 instruction cache. So the execution proceeds correctly on Rocket, with the fetch to 0x8000308a reading the stale data from the L1 ICache.
> 
> In RISC-V, synchronization between writes to instruction memory and instruction fetch by the same hart is not guaranteed unless a `fence.i` instruction is executed between the write and the fetch.

Hi @jerryz123 ! Thank you for your patient explanation. After adding the `fence.i` instruction, I found that the behavior of Rocket is consistent with Spike, so I am closing this issue now. 

Thanks again!
