### ISSUE TITLE
Compiling spike must require c++17

### ISSUE THREAD

**Issue by biglanzi** [riscv/riscv-isa-sim#1571]
I want to know if compiling Spike requires an environment with C++17 or higher. My current environment is gcc 4.8.5, which supports only C++11. When I try to compile Spike, it fails because the source code of Spike uses 'optional,' which is a feature of C++17
thanks

**Comment by chihminchao** [comment]
C++17 is minimal requirement since spike uses some utilities such as "optional" only avaiable after this version

**Comment by biglanzi** [comment]
by the way,my host machine env is centos 7 and gcc 4.8.5
my shell command is 
```
cd spike
mkdir build && cd build
../configure --prefix=$RISCV
make -j 8
```

**Comment by biglanzi** [comment]
> C++17 is minimal requirement since spike uses some utilities such as "optional" only avaiable after this version

okay,thanks 
I checked the closed issues and found that some of them used c++11, so I was a little confused.
now,I got it, c++17 is minimal requirement after the latest version
