### ISSUE TITLE
User fetch segfault  when running spike pk.

### ISSUE THREAD

**Issue by RitikMehta10** [riscv/riscv-isa-sim#1578]
Hey, I wrote a simple code:

```
#include <stdio.h>
int main(void){
int a,b,c;
a=5;
b=3;
c=a*b;
}
```
Spike and pk are already built and i am using an elf compiler.

Then run the following commands:
```
$ riscv64-unknown-elf-gcc -S -o int_mul.s int_mul.c
$ riscv64-unknown-elf-as -o int_mul.o int_mul.s
$ riscv64-unknown-elf-ld -o int_mul int_mul.o
```

this popped a warning:
riscv64-unknown-elf-ld: warning: cannot find entry symbol _start; defaulting to 00000000000100b0
then i did this:

`spike pk int_mul`
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/75519295/b60874a6-1bd3-4d42-a5e5-34424990a8b8)

I wonder if spike can simulate the glibc and how to do it?
Can anyone help me out with this. Thanks!

**Comment by jerryz123** [comment]
You should use the `riscv64-unknown-linux-gnu-gcc` toolchain.

Additionally, binaries compiled to run with pk must be statically linked (use `-static`).
