### ISSUE TITLE
Unknown Exception while testing rv64imac instructions 

### ISSUE THREAD

**Issue by omanzoor** [riscv/riscv-isa-sim#1594]
I have generated RV64IMAC instructions using GoogleDV for core verification. While testing these instructions on Spike, I encountered an unknown issue. It shows an exception like this: **exception trap_illegal_instruction, epc 0x000000008000a002**. and keeps repeating it. I have attached the output log file. 

What could be the issue?

![Screenshot from 2024-02-06 23-29-58](https://github.com/riscv-software-src/riscv-isa-sim/assets/154589058/c9435539-8d79-4a0c-8dbc-91cb311018b2)

[out.0.log](https://github.com/riscv-software-src/riscv-isa-sim/files/14184693/out.0.log)

**Comment by jerryz123** [comment]
The issue is that your trap handler contains an illegal instruction at `0x8000a002`. You can see clearly from the log that the memory there is 0x0.
