### ISSUE TITLE
Got an exception "Load Page Fault" while accessing the U pages, with SSTATUS.SUM=1

### ISSUE THREAD

**Issue by zeeshanrafique23** [riscv/riscv-isa-sim#1597]
Hi, 
I am executing a test on env where machine has U,S, and M-mode implemented. While trying to access (performing load) the User pages, I got an exception "Load Page Fault" whereas the SUM bit in sstatus is set.

**Comment by aswaterman** [comment]
Spike is believed to be correct with respect to this feature, so the odds are good that this a bug in the test program.

Obviously, if it's a Spike bug, we'd like to fix it.  But we can only provide assistance with that if you provide us with straightforward instructions to reproduce the error.

**Comment by zeeshanrafique23** [comment]
Thanks for the clarification. I was expecting the bug might be in the test case. Let me go through the test thoroughly again. I will report here whatever the issue that I am facing, once I am able to find it.

**Comment by aswaterman** [comment]
Cool, do let us know regardless which way it turns out.

**Comment by zeeshanrafique23** [comment]
The test was trying to load the U-mode instruction whose address was expected to be in a particular register but that reg was modified at some place in the code and result into loading the address which is not present in the MMAP.

Thanks for your response.

**Comment by aswaterman** [comment]
You're welcome!
