### ISSUE TITLE
terminate called after throwing instance

### ISSUE THREAD

**Issue by omanzoor** [riscv/riscv-isa-sim#1604]
Here is the .S file of rv63imac instructions which I'm trying to run on spike, but spike is giving error like terminate called after throwing instance:

[riscv_loop_test_0.S.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/14318374/riscv_loop_test_0.S.zip)

/home/icdl/Pictures/Screenshot from 2024-02-17 14-43-11.png

what is the issue and how to resolve it?

**Comment by jerryz123** [comment]
There isn't enough information in this report to act on.
