### ISSUE TITLE
Is there any visualization tools for spike?

### ISSUE THREAD

**Issue by mttbx** [riscv/riscv-isa-sim#1613]
Is there any visualization tools for spike?

**Comment by scottj97** [comment]
I'm not sure what you're looking for. You want to visualize the target program that Spike is executing? Isn't that what a debugger does? You can connect GDB to Spike and use any GDB-supported GUI, iiuc.

**Comment by mttbx** [comment]
No, What I mean is to show the registers in the gui

**Comment by jerryz123** [comment]
Run spike with debug mode ... `spike -d ...`, then type `h` to look at the support interactive debug mode commands.

**Comment by mttbx** [comment]
Thank you. I'll try this.
