### ISSUE TITLE
spike decodes incorrectly in v-u mode

### ISSUE THREAD

**Issue by zhangkanqi** [riscv/riscv-isa-sim#1622]
Hi,
When I ran test.elf in spike, I found that spike decoded an instruction incorrectly.

In detail, there is an `auipc` instruction at pc=0x80000174 in test.dump. 
```assembly
80000174:	00000f17          	auipc	t5,0x0
```
However, when running test.elf in spike, that instruction was decoded as `c.unimp` in virtual address mode. We can get this information in test.log.
```assembly
core   0: 0xffffffffffe00174 (0x00000000) c.unimp
core   0: exception trap_illegal_instruction, epc 0xffffffffffe00174
core   0:           tval 0x0000000000000000
```

So, I wonder why spike decodes `auipc` as `c.unimp`? Is this a bug?

For reproduction, you can run the following command at commit e46586e2b5744c631e4fefede8df9f0108f06b8d :
```bash
spike--isa=rv64gcv -l --log-commits --log "test.log" test.elf
```

Here are the files you will need:
[spike_decode_incorrectly.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/14557102/spike_decode_incorrectly.zip)

**Comment by jerryz123** [comment]
This is almost certainly a software bug. The disassembly is displaying correctly, as the log tells you that the data at the instruction address `0xffffffffffe00174` is`0x00000000`.

**Comment by zhangkanqi** [comment]
Thanks, but I have no idea why does this problem happen. 
The expected value for the instruction at address 0xffffffffffe00174 should be 0x00000f17, correct?

**Comment by omerguzelelectronicguy** [comment]
you can check the previous part of your execution to see whether there is a store to that address or not. This happens to me a lot. Be careful about the address, because it doesn't have to be the same address to update your previous command. we are seeing the virtual address in spike so you should check the physical address of that instruction.
