### ISSUE TITLE
Incorrect upward rounding result of `fsub.s` instruction

### ISSUE THREAD

**Issue by zhangkanqi** [riscv/riscv-isa-sim#1625]
Hi,

When executing the `fsub.s ft5, ft5, ft2, rup` instruction in Spike, I found that the result is incorrect, where ft5 is initialized as 0x284d52df and ft2 is initialized as 0x7b418a35.
I believe the correct final result in ft5 should be 0xfb418a35 (as Intel does), however, the result calculated in Spike is 0xfb418a34.

**Comment by aswaterman** [comment]
Intel produces 0xfb418a34, too:

```
$ cat test.c
#include <stdio.h>
#include <fenv.h>

int main()
{
  volatile int a = 0x284d52df;
  volatile int b = 0x7b418a35;
  volatile float f = *(volatile float*)&a;
  volatile float g = *(volatile float*)&b;

  fesetround(FE_UPWARD);
  volatile float h = f - g;

  printf("%x\n", *(volatile int*)&h);

  return 0;
}
$ gcc -O2 -lm test.c && ./a.out
fb418a34
```

**Comment by aswaterman** [comment]
It makes sense that, when rounding upward, the result would be 0xfb418a34 if the true result lies between 0xfb418a35 and 0xfb418a34, since the latter number is greater than the former.

**Comment by zhangkanqi** [comment]
```cpp
$ cat main.cpp
#include <iostream>
#include <iomanip>
#include <cstdint>
#include <cstring>
#include <cmath>


// 函数声明
float hexToFloat(uint32_t hex);
uint32_t floatToHex(float value);

int main() {
    // 浮点数的十六进制表示
    uint32_t hex1 = 0x284d52df;
    uint32_t hex2 = 0x7b418a35;

    // 计算减法结果
    float result = hexToFloat(hex1) - hexToFloat(hex2);

    // 向上舍入
    if (result < 0) {
        result = ceilf(result);
    } else {
        result = floorf(result);
    }

    // 打印结果的十六进制表示
    uint32_t result_hex = floatToHex(result);
    std::cout << "最终结果的十六进制表示为: 0x" << std::hex << std::setw(8) << std::setfill('0') << result_hex << std::endl;

    return 0;
}

// 将十六进制表示的浮点数转换为浮点数
float hexToFloat(uint32_t hex) {
    float result;
    std::memcpy(&result, &hex, sizeof(float));
    return result;
}

// 将浮点数转换为十六进制表示并返回
uint32_t floatToHex(float value) {
    uint32_t result;
    std::memcpy(&result, &value, sizeof(uint32_t));
    return result;
}

$ g++ main.cpp -o main; ./main
最终结果的十六进制表示为: 0xfb418a35

```
Is there something wrong with main.cpp?

My processor model is Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz, Little Endian

**Comment by aswaterman** [comment]
You didn't set the rounding mode.  The default rounding mode is round-to-nearest, ties-to-even.  If you want to select round-up, you need to do so explicitly.  (See my source code.)

**Comment by zhangkanqi** [comment]
Sorry, I have modified man.cpp(as the codes above) . But the result is still 0xfb418a35. I am trying your code.

**Comment by aswaterman** [comment]
Computing the result then taking the ceil/floor does not have the same effect as setting the rounding mode, for multiple reasons.  Anyway, this isn't a Spike bug.

**Comment by zhangkanqi** [comment]
Oh! I get it! Sorry, I misunderstand the underlying meaning of rounding mode.
In some implementations, the result will indeed be 0xfb418a35, which is an inaccurate result.  But actually, 0xfb418a34 is more precise.

Thanks for your reply.
