### ISSUE TITLE
Counter-intuitive MMIO device arguments behavior

### ISSUE THREAD

**Issue by liuyu81** [riscv/riscv-isa-sim#1652]
PR #1522 introduced a feature to pass down extra arguments to device plugins.

The original PR motivated this feature with the following use case,

> The ucb-bar block device is implemented as an MMIO device.
We would like to pass an argument to the block device such that it can read a file and initialize its contents at startup.

Our intuition was that, device arguments should apply to device instances (`abstract_device_t`). Say, if we specify two devices each taking a different set of arguments, i.e.,

```
spike --extlib=myplugin.so --device=mydevice,args=first_input_file --device=mydevice,args=second_input_file ...  
```

we would expect `spike` to register *one* device factory (`device_factory_t`) under the name `mydevice`, and *two* device instances (`abstract_device_t`) specialized with different sets of arguments.

Surprisingly, based on what we observed from the implementation (`spike_main/spike.c:L357-377`), device arguments are actually per-factory (as opposed to per-device). And, if specified more than once, the *last* set of arguments takes effect for *all* device instances. So, in the above example, we end up with *two* `mydevice`'s, both wired to the `second_input_file`.

Of course, to work around, one can register the same device factory multiple times under different names. But still, the CLI `--device` option is a bit counter-intuitive here, and, IMHO, when the arity is always one device per factory, it probably invalidates the use of the factory pattern in the first place.

**Comment by jerryz123** [comment]
Yes, this is indeed a limitation with the current system. I agree it is far more intuitive to support instantiating multiple instances of the same device.

- `device_factory_t::parse_from_fdt` would have to return a vector of device pointers
- devices for which there should never be multiple instances (CLINT/PLIC) should assert this
- `device_factory_t::set_sargs` should be `add_sargs`, I think.
- `device_factory_t::sargs` should be a 2D object - a list of argument-lists.
- `device_parser` in `spike_main` should use `add_sargs` instead of `set_sargs`

We'd probably want a address-map sanity checker across all instantiated devices too.

I'd be happy to review this PR if it were made, and make any modifications to our `ucb-bar/spike-devices` to conform to the updated APIs.

**Comment by liuyu81** [comment]
I would be happy to help with refactoring the MMIO device API, but would propose a slightly different design.

If you consider the life-scope of `sargs` versus device factories: `sargs` are collected in CLI `main`, and consumed by `sim_t`'s constructor -- their lives are bound to exactly one `sim_t` instance; device factories, on the other hand, are instantiated and registered globally to `mmio_device_map_t` -- their lives may well span multiple `sim_t` instances (given that using `libriscv.so` is a supported feature).

As it seems to me, `mmio_device_map_t` is more of a global registry of all available MMIO device models. And each `sim_t` is typically only using a specialized subset of device models -- as suggested by the `plugin_device_factories` argument to `sim_t`'s constructor. In this regard, by calling the `set_sargs` (`add_sargs`) method of a device factory, we are literally promoting device-specific `sargs` to global scope -- and introducing *states* to device factories. If we ever need to instantiate a second `sim_t` instance (as we did in our primary use case of `libriscv.so`), we would have to wipe out pre-existing `sargs` -- an extra burden of state management.

Now, if `sargs` are device-specific, and are not meant to be shared across multiple `sim_t` instances, how about localizing them inside CLI main, and passing them to `generate_fdt` / `parse_from_fdt` via an extra input argument?

```diff
class device_factory_t {
public:
-  virtual abstract_device_t* parse_from_fdt(const void* fdt, const sim_t* sim, reg_t* base) const = 0;
+  virtual abstract_device_t* parse_from_fdt(const void* fdt, const sim_t* sim, reg_t* base, const std::vector<std::string>& sargs) const = 0;
-  virtual std::string generate_dts(const sim_t* sim) const = 0;
+  virtual std::string generate_dts(const sim_t* sim, const std::vector<std::string>& sargs) const = 0;
  virtual ~device_factory_t() {}
-  void set_sargs(std::vector<std::string> sargs) { this->sargs = sargs; }
-  std::vector<std::string> get_sargs() { return sargs; }
-
-protected:
-  std::vector<std::string> sargs;
};
````

As such, the semantics and return types of  `generate_fdt` / `parse_from_fdt` remain intact. Device factories become stateless (I believe they used to be `const` before #1522). And since `generate_fdt` / `parse_from_fdt` are only ever invoked in `sim_t`'s constructor, we only need to pass down `sargs` from CLI main to `sim_t`'s constructor in a modified version of `plugin_device_factories`, i.e.,

```diff
+ using device_factory_sargs_t = std::pair<const device_factory_t*, std::vector<std::string>>;

class sim_t : public htif_t, public simif_t
{
public:
  sim_t(const cfg_t *cfg, bool halted,
        std::vector<std::pair<reg_t, abstract_mem_t*>> mems,
-        std::vector<device_factory_t*> plugin_device_factories,
+        const std::vector<device_factory_sargs_t>& plugin_device_factories,
        const std::vector<std::string>& args,
```

Please let me know what you think about this proposed change. If you'd agree that we take this approach, I would be happy to prepare a PR.

**Comment by jerryz123** [comment]
This approach looks good to me. Making `device_factory_t` const, and globally reusable, is a nice benefit.
