### ISSUE TITLE
Spike setting VTYPE to 0x8000000000000000 for e16 mf8

### ISSUE THREAD

**Issue by FariaaFaheem** [riscv/riscv-isa-sim#1654]
For e16(001), mf8(101) shouldn't VTYPE be set to 13 (1101), rather my spike is setting the vill bit to 1. Also isn't this combination e16, mf8 legal?

core   0: 0x0000000800000784 (0x00d372d7) vsetvli t0, t1, e16, mf8, tu, mu
core   0: 0 0x0000000800000784 (0x00d372d7) c8_vstart 0x0000000000000000 x 5 0x0000000000000000 c3104_vl 0x0000000000000000 **c3105_vtype 0x8000000000000000** c768_mstatus 0x8000000a00006680
:

**Comment by aswaterman** [comment]
The spec says "For a given supported fractional LMUL setting, implementations must support SEW settings between SEWMIN and LMUL * ELEN, inclusive."

For SEWMIN=8, LMUL=1/8, and ELEN=64, this means that only SEW=8 is required to be supported.  So, it is valid for Spike to reject the mode you've attempted to select by setting vill.
