### ISSUE TITLE
spike doesn't update sepc and stval in virtual address mode

### ISSUE THREAD

**Issue by zhangkanqi** [riscv/riscv-isa-sim#1666]
Hi,

I find that when spike encounter an exception in virtual address, it doesn't update  sepc and stval, but Boom does.

![屏幕截图 2024-05-13 112907](https://github.com/riscv-software-src/riscv-isa-sim/assets/34207592/fb797a97-dda4-441a-9f7b-939e075f7369)

The final result of spike(ISA) and Rocket(RTL) is:
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/34207592/b4b8e2c1-9cc0-4882-aff1-9ec63d649d00)

spike version: e46586e2b5744c631e4fefede8df9f0108f06b8d
elf file: 
[input_0.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/15289166/input_0.zip)

**Comment by jerryz123** [comment]
That trap is taken into M-mode, so mepc and mtval are written.

The BOOM behavior is likely a bug, albeit a surprising one.

**Comment by jerryz123** [comment]
I was not able to cleanly reproduce your issue in the RTL either. Please open an issue against the BOOM repo with steps to reproduce the divergence.

**Comment by zhangkanqi** [comment]
Thanks for your reply.
Sorry, I made a mistake, the RTL refers to Rocket, not BOOM. I have opened an issue about this divergence on Rocket, attached with debug files.

**Comment by aswaterman** [comment]
I highly doubt this is a bug in Rocket, either. Sounds like different configuration (which exceptions are delegable etc.).

**Comment by zhangkanqi** [comment]
Actually, it seems due to the different implementation of exceptions priority between Rocket and Spike.
This `fsd` instruction can cause both two types of exceptions, store addr misaligned and store page fualt. Spike prefers store addr misaligned exception has higher priority than store page fualt, but Rocket takes the opposite. Therefore, different exceptions are taken into different mode(M or S).
<img src="https://github.com/riscv-software-src/riscv-isa-sim/assets/34207592/387627ca-4f4d-404b-8ac7-097e4999a0b8" width="60%">
See Rokcet's behavior: https://github.com/chipsalliance/rocket-chip/issues/3629

Thanks for your all replies.
