### ISSUE TITLE
Parse Zve/Zvl to determine RVV settings, instead of --varch

### ISSUE THREAD

**Issue by jerryz123** [riscv/riscv-isa-sim#1671]
The standard mechanism for communicating vector unit capabilities for VLEN and ELEN is through the Zvl and Zve extension strings.

**Comment by aswaterman** [comment]
Agreed.  I think `--varch` might've predated that aspect of the vector ISA.

(FYI @chihminchao, since this affects the command-line interface)

**Comment by jerryz123** [comment]
Resolved by #1701
