### ISSUE TITLE
for vl=0 does vfredsum need to make vd[0]=vs1[0]?

### ISSUE THREAD

**Issue by xinyuwang-starfive** [riscv/riscv-isa-sim#1673]
![7b3f8f54fb214d2ad6338dd41e8c5a90](https://github.com/riscv-software-src/riscv-isa-sim/assets/37825795/d644febf-6db5-4419-805c-766e72c9e938)
the spec say no element are active,the scalar in vs1[0] copied to vd[0]. 
if vl=0，does the vfredsum need to make vd[0]=vs1[0]

**Comment by aswaterman** [comment]
No, Spike is correct in this case.  The highlighted text is describing the case that vstart < vl but no elements are unmasked.  Also it's non-normative text.  The general statement that "if vstart >= vl, no destination registers are written" is determinative.
