### ISSUE TITLE
Facing Issue running Zvbb RVV Cryptography Instructions

### ISSUE THREAD

**Issue by akifejaz** [riscv/riscv-isa-sim#1676]
I'm trying to run the Vector Bit-manipulation Zvbb on spike but I'm facing issue. Spike says 'trap_illegal_instruction', this is how I'm running test, I'm I missing something?
`spike --isa=RV64gcV -d --varch=vlen:2048,elen:64 -m0x100000000:0x800000000 unary_crypto_m1_e32_md1_0/test.elf` 

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/81078376/4bdffc1e-2d9a-4e88-92b5-037a3530c909)

Can you please help me with this please?
@arunthomas @scottj97

**Comment by aswaterman** [comment]
The ISA string you specified doesn't include Zvbb.  Try using `--isa=rv64gcv_zvbb` instead.

**Comment by akifejaz** [comment]
> The ISA string you specified doesn't include Zvbb. Try using `--isa=rv64gcv_zvbb` instead.

Is there a single ISA flag for enabling whole crypto since there are different extensions under crypto spec. as in image below. For example. VCLZ works when I'm adding `--isa=rv64gcv_zvbb` and VAESEF works when I'm adding `--isa=rv64gcv_zvkend` Can I add single ISA flag for all these instructions supported? Thanks alot.

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/81078376/4012adb5-ee07-43e7-ae74-4be3bdbc2a27)

**Comment by aswaterman** [comment]
You’ll have to consult the ISA specs to see which extensions include which instructions. Spike conforms to that spec.
