### ISSUE TITLE
Vector Widening Integer Multiply-Add Instructions - not working

### ISSUE THREAD

**Issue by deepaannnavi** [riscv/riscv-isa-sim#1681]
> worked in vector widening mac instruction 

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/78bbcd27-feaf-439b-b9f7-745acc5fda0b)
set element width as e = 64, LMUL =1
loading the 32 bit element to v1 vector register
loading the 32 bit element to v0 vector register
loading the 64 bit element to v8 vector register
vwmaccu.vv do the unsigned multiplication(v0*v8) and add the result to v8 vector register and store the result to the v8 vector register

> disassembly file output:

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/9bc2efbd-6dae-42c4-939b-c79e509d105d)

> Dump file output shows as:

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/82d97984-3965-496d-9da3-3ebd30435544)
 
here v0,v1,v8 vector register got loaded, but the vector widening Integer multiply add instruction doesn't work.
It throws mcause 2 which tells it is illegal instruction. 
can anyone resolve this and help me telling how to make this instruction work without error

**Note**

> spike commit :[a53a71f](https://github.com/riscv-software-src/riscv-isa-sim/commit/a53a71fcc3c985cf95973e86e40814c30c551a68)

>command: spike --log-commits --log spike.dump +signature=spike_signature.txt ${Test_file_NAME}.elf`

**Comment by aswaterman** [comment]
Widening multiplies use SEW for the inputs and 2xSEW for the outputs. So you're trying to do a 64->128 multiply, which is not supported.  You need to set SEW=32.

**Comment by deepaannnavi** [comment]
Thank you so much it worked now

> risc v assembly code:
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/f784f228-1869-493d-8027-69f693ecfe0c)

> disassembly file
![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/b9c3bd9f-95fd-462a-a72f-862564c801d1)

> dump file:

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/144416964/a86a24cf-233e-4371-bae9-74442d682026)
