### ISSUE TITLE
assert failed in vectorUnit.cc from 71line. T&vectorUnit_t::elt(reg_t,reg_t,bool)[with T=long unsigned int; reg_t=long unsigned int]: Assertion '(VLEN>>3)/sizeof(T)>0' failed.

### ISSUE THREAD

**Issue by huihuiei** [riscv/riscv-isa-sim#1685]
in my testbench, spike is as reference model through dpi interface into my entirement. I set "vlen:32,elen:32", in static cfg_t cfg(std::make_pair(0,0)......) function. but the simulation will stop because the error: T&vectorUnit_t::elt(reg_t,reg_t,bool)[with T=long unsigned int; reg_t=long unsigned int]: Assertion '(VLEN>>3)/sizeof(T)>0' failed.
except the cfg_t cfg function, which function should i change or transfer?

**Comment by aswaterman** [comment]
Sorry, we can’t offer support for this sort of use case because we can’t replicate the problem ourselves. If you can replicate the bug with vanilla Spike, please reopen the ticket.

**Comment by huihuiei** [comment]
i think you could replicate this problem. set varch 32,32. then execute: vsetivli a2, 0x1, e32,  vmv.v.x v0, t1; then there will be the same error.

**Comment by aswaterman** [comment]
We haven’t put effort into supporting VLEN=ELEN configs, so it’s at least conceivable this is a limitation of vanilla Spike. But I don’t have resources to look into it for now. Submit a PR if you can.

cc @chihminchao
