### ISSUE TITLE
issue in counting numbers of instructions

### ISSUE THREAD

**Issue by Sanoj-S-Vijendra** [riscv/riscv-isa-sim#1686]
So, I have to count the number of instruction executed in the region of interest of my cpp code using this spike simulator. I have defined the region of interest as : 
```

static inline __attribute__((always_inline)) void Start_ROI()
{
   __asm__ volatile("srai zero, zero, 0");
}

my required code

static inline __attribute__((always_inline)) void End_ROI()
{
   __asm__ volatile("srai zero, zero, 1");
}
```

**How to do this?**

**Comment by jerryz123** [comment]
There's many examples of code sequences which do this. For instance, the benchmarks in https://github.com/riscv-software-src/riscv-tests
