### ISSUE TITLE
Reading macro RD behave unexpected

### ISSUE THREAD

**Issue by Lesliehsyu** [riscv/riscv-isa-sim#1707]
I want to add one custom instruction that requires modifying some bits in the destination register and keeping the other parts of the register untouched. I saw a macro defined in `riscv/decode_macro.h` that, the macro `RD` could read from the destination register.

```c
    uint32_t a,b,c;
    a = 0xdbeef000;
    b = 0xdeadb;
    c = 0xdead;
    asm volatile
    (    
    "[custome_instruction]   %[z], %[x], %[y]\n\t"
    : [z] "=r" (c)
    : [x] "r" (a), [y] "r" (b));
```
Inside this instruction, I used the macros to print the interim values during this instruction using

```C
printf("original value of rd=%x\n",RD);
printf("original value of rs1=%x\n",RS1);
printf("original value of rs2=%x\n",RS2);
```

And the result is 

```
original value of rd=dbeef000
original value of rs1=dbeef000
original value of rs2=deadb
```

The result of rd is not correct, is there any solution to reading the value from the destination register in Spike?

**Comment by aswaterman** [comment]
It looks like you are misusing inline asm; i.e. this is not a Spike problem.

Using `=r` means that `c` is only an output, not an input, and so the compiler does not care about the previous value.  So the statement `c = 0xdead;` has no effect.  If you use `+r` instead, which means `c` is both an input and an output, then the code will probably do what you want.
