### ISSUE TITLE
Deprecated dcsr.halt

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-isa-sim#1727]
Hello,

To my knowledge, the dcsr_csr_t::halt variable is for halt_on_reset, i.e., the -H flag for the debugger. Spike leaves a backdoor for altering the halt variable, i.e., writing a read-only bit, dcsr.nmip (riscv/csrs.cc:1357). 
```  halt = get_field(val, DCSR_NMIP);```

Given that this backdoor isn't generally specified in the specification, it raises an interesting question: Is this backdoor typically required for the openOCD?
@rtwfroody Would you share some words about this?

(A branch decouples the halt variable from the dcsr.nmip. https://github.com/riscv-software-src/riscv-isa-sim/pull/1726)

Best regards,
YenHaoChen

**Comment by rtwfroody** [comment]
dcsr.halt is ancient, and nowhere to be found in any recent debug spec. (E.g. I have a 2019 version here that doesn't include include this bit.) AFAIK OpenOCD does not require this, and if it does then it's a bug in OpenOCD.

**Comment by YenHaoChen** [comment]
@rtwfroody Thanks for your clarification.
