### ISSUE TITLE
From double trap spec, we saw that Ssdbltrp adds an SDT field to sstatus. But will mstatus has this bit?

### ISSUE THREAD

**Issue by Madman-Hugo** [riscv/riscv-isa-sim#1751]
![image](https://github.com/user-attachments/assets/b058e167-5fbb-48bd-bc49-5d4127599eef)

**Comment by aswaterman** [comment]
Yes, as the spec says, `sstatus` is a subset of `mstatus`, so if `sstatus` has something, `mstatus` has it, too.  Also, note that the `mstatus` diagram includes the `SDT` bit:

![Screenshot 2024-07-31 at 2 43 11 PM](https://github.com/user-attachments/assets/787df108-557c-4eb8-9bcf-3ab9c2bd3323)

**Comment by Madman-Hugo** [comment]
ok  thanks
