### ISSUE TITLE
`fsqrt.s` with zero source register results `NaN` instead of `0`

### ISSUE THREAD

**Issue by riscv914** [riscv/riscv-isa-sim#1765]
**Type of issue:** bug report

**Impact:** unexpected behavior

**Other information**

Executing Single-Precision fsqrt with a `zero` source value on the spike results in a NaN value (`0x7fc00000`) while it should be `zero`. For more information, I attached a sequence of instructions to reproduce.

**Execute following instruction:**
```
fmv.w.x ft4, zero
fmv.w.x ft5, zero
fsqrt.s ft5, ft4 // if check ft5 after this instruction it is `0xffffffff7fc00000`
```

**What is the current behavior?**
The destination value should be zero.

**Environment:**
- Spike version: `1.1.1-dev`
- Spike commit: `2890ea72125b69eb96bb0458a5bbc00ce26e8872`

**Comment by aswaterman** [comment]
I observe the correct behavior:

```
core   0: 0x0000000080000150 (0xf0000253) fmv.w.x ft4, zero
core   0: 0x0000000080000154 (0xf00002d3) fmv.w.x ft5, zero
core   0: 0x0000000080000158 (0x580272d3) fsqrt.s ft5, ft4
(spike) fregs 0 ft5
0
(spike) freg 0 ft5
0xffffffffffffffffffffffff00000000
```

**Comment by riscv914** [comment]
> I observe the correct behavior:
> 
> ```
> core   0: 0x0000000080000150 (0xf0000253) fmv.w.x ft4, zero
> core   0: 0x0000000080000154 (0xf00002d3) fmv.w.x ft5, zero
> core   0: 0x0000000080000158 (0x580272d3) fsqrt.s ft5, ft4
> (spike) fregs 0 ft5
> 0
> (spike) freg 0 ft5
> 0xffffffffffffffffffffffff00000000
> ```

Thank you for your reply.
Sorry the `ft4` value should be 0x7fffffff00000000 (which is still zero for fsqrt.s). Please try following instructions:
```
asm volatile ("fmv.w.x fs7, zero");
asm volatile ("fsgnjn.d ft4, fs7, fs7");
asm volatile ("fmv.w.x ft5, zero");
asm volatile ("fsqrt.s ft5, ft4 ");
```

**Comment by aswaterman** [comment]
`0x7fffffff00000000` is not a properly boxed single-precision value, so it is not true that is considered 0 for `fsqrt.s`.  It is interpreted as a NaN input.  See https://github.com/riscv/riscv-isa-manual/blob/main/src/d-st-ext.adoc#nan-boxing-of-narrower-values

Spike is correct.
