### ISSUE TITLE
`fdiv.s` with a dynamic rounding mode set to `REN` on the spike results in a incorrect rounding

### ISSUE THREAD

**Issue by riscv914** [riscv/riscv-isa-sim#1772]
**Type of issue:** bug report

**Impact:** unexpected behavior

**Other information**

Executing Single-Precision `fdiv.s` with a dynamic REN rounding mode on the spike results in a incorrect rounding. For more information, I attached a sequence of instructions to reproduce.

**Execute following instruction:**
```
lui  s10, 0x0
csrw fcsr, s10 // set zero for rounding mode (REN Round to Nearest, ties to Even)
lui     s4, 0x5b365
fmv.w.x fs0, s4
lui     t5, 0x34bc9
fmv.w.x fs10, t5
fdiv.s   fs7, fs10, fs0 // fs7 0xffffffff19046359
```

**What is the current behavior?**
The destination value should round to even number `0xffffffff19046358` however it is rounding to odd number `0xffffffff19046359`.

**Environment:**
- Spike version: `1.1.1-dev`
- Spike commit: `6f28e4bee53b3c49d6b3b06db5989bc5ec7933f4`

**Comment by aswaterman** [comment]
I think you're misunderstanding IEEE 754's definition of round-to-nearest with ties to even.  You'll observe that you get the same result on an x86 or ARMv8 machine:


```
$ cat test.cc
#include <stdio.h>
#include <inttypes.h>
#include <fenv.h>

#pragma STDC FENV_ACCESS ON


int main()
{
  fesetround(FE_TONEAREST);

  union u {
    uint32_t i;
    float f;
  };

  volatile u f = { .i = 0x34bc9000 };
  volatile u g = { .i = 0x5b365000 };

  u fu = { .f = f.f / g.f };

  printf("%" PRIx32 "\n", fu.i);

  return 0;
}
$ g++ -O2 test.cc && ./a.out
19046359
```
