### ISSUE TITLE
Discrepancy with respect to maskmax field in mcontrol (spec vs spike)

### ISSUE THREAD

**Issue by RaamyPi** [riscv/riscv-isa-sim#1785]
From the spec (Version 1.0.0-rc3, Revised 2024-05-15), Page 72,

> A value of 0 indicates match 1 is not supported

but in spike's implementation (latest), maskmax is tied to zero but match == 1 (NAPOT) is also supported at the same time.

**Comment by aswaterman** [comment]
cc @YenHaoChen @rtwfroody

**Comment by YenHaoChen** [comment]
@RaamyPi Thanks for reporting the issue. I provided a PR for the problem. Please let me know if you have any further concerns.

**Comment by raamypi** [comment]
Thanks for the help!
