### ISSUE TITLE
Ssdbltrp - VS mode double trap check

### ISSUE THREAD

**Issue by lewislzh** [riscv/riscv-isa-sim#1799]
In Spike's double trap check for VS/S mode, the current code accesses `state.nonvirtual_sstatus` in VS mode and `state.sstatus` in S mode.
    [processor.cc#L447-L453](https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/processor.cc#L447-L453)
I think this reverses the intended access to the VS/S status registers, preventing the correct execution of double traps in VS mode. 
Moreover, I think it might not be necessary to use curr_virt to select between VS and S status registers. 
Spike inherently supports accessing `sstatus` based on the current virtualization mode, reading from either `sstatus` or `vsstatus` as appropriate.
Therefore, we might consider adjusting line 466 to: `reg_t s = state.sstatus->read();`

**Comment by aswaterman** [comment]
@ved-rivos can you take a look at this?

**Comment by ved-rivos** [comment]
> I think this reverses the intended access to the VS/S status registers, preventing the correct execution of double traps in VS mode

Yes. Thanks for spotting that.

> Therefore, we might consider adjusting line 466 to: reg_t s = state.sstatus->read();

I am not sure that is right. Please see use of nonvirtual_sstatus vs. sstatus in rest of the function.

I sent a PR #1804 to swap it. @aswaterman please let me know if its right to just use sstatus->read(). Will it resolve to the sstatus or vstatus internally?

**Comment by aswaterman** [comment]
@ved-rivos I'll follow up on the PR.

**Comment by ved-rivos** [comment]
@aswaterman - Thanks. I have updated the PR.
