### ISSUE TITLE
Default `pmpcfg0 = 0x000000000000001f` and `pmpaddr0 = 0x003fffffffffffff`.

### ISSUE THREAD

**Issue by ha0lyu** [riscv/riscv-isa-sim#1803]
If we do nothing but read the `pmpcfg{0,2,4,6,8,10,12,14}` and `pmpaddr[i]`, we will see the `pmpcfg0 = 0x000000000000001f` and `pmpaddr0 = 0x003fffffffffffff`. The rest registers are all `0x0000000000000000`.
![Test result](https://github.com/user-attachments/assets/c97080ff-6176-42de-8407-8d13dd18c346)

[Here](https://github.com/user-attachments/files/16980302/spike_pmp.txt) is a test program.

**Comment by aswaterman** [comment]
There’s no bug here. The reset value of the PMP registers is platform-defined. Spike does this for backwards compatibility with old software that wasn’t PMP-aware. If you don’t like these values, your software can overwrite them.

**Comment by ha0lyu** [comment]
Hi @aswaterman, thanks for your replying. I agree with you, it's not a bug. I was confused by this, but now I am clear. Thanks. 
I have read the chapter in the latest version manual **3.7.1. Physical Memory Protection CSRs**. But I am not totally understood PMP yet. What if the reset value of the PMP registers in a CPU is not all zero when the CPU starts, such as: `pmpcf{i} = 0x00`, but `pmpaddr{j} != 0x00`, is it a bug?

**Comment by TheSaltyLiquorice** [comment]
> Hi @aswaterman, thanks for your replying. I agree with you, it's not a bug. I was confused by this, but now I am clear. Thanks. 
> I have read the chapter in the latest version manual **3.7.1. Physical Memory Protection CSRs**. But I am not totally understood PMP yet. What if the reset value of the PMP registers in a CPU is not all zero when the CPU starts, such as: `pmpcf{i} = 0x00`, but `pmpaddr{j} != 0x00`, is it a bug?

If the reset of the csr prevents M mode code from running, that would be fatal. For example, if pmpaddr0 was all ones, address matching mode tor, the lock bit is set, and X permissions are missing that would prevent the cpu from doing anything useful forever.

On the other hand, as long as the L bit isn't set, machine mode software can do as it pleases with the pmp configuration.

**Comment by aswaterman** [comment]
Right.  The platform can specify a nonzero reset value for some PMP registers, and it's the platform's responsibility not to specify a reset value that would prevent the processor from functioning (e.g. @TheSaltyLiquorice's example).

**Comment by ha0lyu** [comment]
Thank you all for clarifying my doubts.
