### ISSUE TITLE
CSRRWI Shouldn't be updating CSR if "uimm" field is 0

### ISSUE THREAD

**Issue by FluxByt** [riscv/riscv-isa-sim#1813]
According to spec:
```
if the uimm[4:0] field is zero, then these instructions will not write to the CSR,
and shall not cause any of the side effects that might otherwise occur on a CSR write, nor raise illegal-
instruction exceptions on accesses to read-only CSRs.
```

However within [riscv/insns/csrrwi.h](../blob/master/riscv/insns/csrrwi.h), This check isn't done therefore always writing to the csr's.

**Comment by DavidYu360** [comment]
The behavior you mentioned is only for CSRRSI and CSRRCI.
Also in the Table 8, CSRRWI always writes to CSR.
![snapshot_table_8](https://github.com/user-attachments/assets/6daabe16-cf87-4cc4-aea4-a3465269fe2c)

**Comment by FluxByt** [comment]
I see, I merged the two sentences while reading, sounds good thank you!
