### ISSUE TITLE
Getting instruction/memory trace of a program

### ISSUE THREAD

**Issue by AnaBSF** [riscv/riscv-isa-sim#1831]
Hi, I wish to use Spike to obtain the instruction and memory traces of a program, which I realise is possible through the -l and --log-commits flags. However, the obtained traces include instructions from outside the programme, and I assume they belong to the proxy kernel.

Is there a way to get the instruction log or commit log without the PK instructions?

**Comment by jerryz123** [comment]
It should be straightforwards to filter out the instruction log by PC to get only user instructions.
