### ISSUE TITLE
mstatus can update mstatus.sdt and mstatus.sie at the same time, but sstatus cannot, is this match the expection?

### ISSUE THREAD

**Issue by ProssMou** [riscv/riscv-isa-sim#1838]
![image](https://github.com/user-attachments/assets/3fe69967-a518-4498-8ae7-d5aad7c90f73)
for writing sstatus, there is a logic to ensure when writing sstatus.sdt to 1, sstatus.sie cannot be write to 1.
but when writing mstatus, there is no according logic, which makes it possible to write mstatus.sdt and mstatus.sie to 1 at the same time, Is the expected or a bug?

**Comment by aswaterman** [comment]
@ved-rivos can you look into this one?

**Comment by ved-rivos** [comment]
@ProssMou - thanks. 
@aswaterman - i sent PR #1839 to address this.
