### ISSUE TITLE
Question about the relation between mstatus.SDT and sstatus.SDT

### ISSUE THREAD

**Issue by SongWYE** [riscv/riscv-isa-sim#1854]
Hi, as a user of the newest version of SPIKE, I want to ask a question about the relation between `mstatus.SDT` and `sstatus.SDT`, which are introduced by the Ssdbltrp extension. 
The spec states: 
> when `menvcfg.DTE` is 0, the implemention should behave as if the Ssdbltrp extension is not implemented and `sstatus.SDT` is read-only zero.

So why is `mstatus.SDT` is still writable in  SPIKE when `menvcfg.DTE` is 0? I thought `mstatus.SDT` and `sstatus.SDT` are exactly the same bit; `sstatus` is just a restricted view of `mstatus` for S mode, so they should both be read-only 0 if `menvcfg.DTE` is 0.

**Comment by ved-rivos** [comment]
`menvcfg` register controls behavior of the execution environment for privilege modes less than M. It does not affect execution in privilege mode M. When `menvcfg.DTE` is 0, the implementation behaves as if Ssdbltrp is not implemented for privilege modes less than M.

**Comment by SongWYE** [comment]
> `menvcfg` register controls behavior of the execution environment for privilege modes less than M. It does not affect execution in privilege mode M. When `menvcfg.DTE` is 0, the implementation behaves as if Ssdbltrp is not implemented for privilege modes less than M.

Thank you very much for your answer.
