### ISSUE TITLE
Question about setting sstatus.SDT after executing MRET instructions

### ISSUE THREAD

**Issue by myx922** [riscv/riscv-isa-sim#1857]
Hi, as a user of the newest version of SPIKE, I'm confused about SPIKE's handling of sstatus.SDT after MRET. 
In M mode, menvcfg.DTE=1, mstatus.SDT=1, sstatus.SDT=1, mstatus.MPV=1, mstatus.MPP=3, execute MRET.
My opinion is that the new privilege mode is M mode， according to spec, sstatus.SDT should still be 1.
However, in this session, SPIKE sets sstatus.SDT to 0 after MRET, so I want to know if SPIKE's handling is wrong?
The spec state:
> The MRET instructions sets sstatus.SDT to 0, if the new privilege mode is U, VS, or VU. Additionally, if it is VU, then vsstatus.SDT is also set to 0.
> The MPV bit (Machine Previous Virtualization Mode) is written by the implementation whenever a trap is taken into M-mode. Just as the MPP field is set to the (nominal) privilege mode at the time of the trap, the MPV bit is set to the value of the virtualization mode V at the time of the trap. When an MRET instruction is executed, the virtualization mode V is set to MPV, unless MPP=3, in which case V remains 0.

**Comment by ved-rivos** [comment]
> so I want to know if SPIKE's handling is wrong?

Yes, the handling in spike is wrong. The `prev_virt` should have been qualified by `prev_prv`. A fix is in #1859

**Comment by myx922** [comment]
> > so I want to know if SPIKE's handling is wrong?
> 
> Yes, the handling in spike is wrong. The `prev_virt` should have been qualified by `prev_prv`. A fix is in #1859

Thank you very much for your answer.
