### ISSUE TITLE
Question about the relation between SIE and SDT?

### ISSUE THREAD

**Issue by myx922** [riscv/riscv-isa-sim#1858]
Spec points out that if SDT is set to 1 or is already 1, SIE cannot be 1. And if menvcfg.DTE is zero, sstatus.SDT is read-only zero.
I'm confused that when menvcfg.DTE=0,  and mstatus.SDT is set to 1, if sstatus.SIE can be set to 1? what about mstatus.SIE?
In other words,  what limits SIE?  SDT or SDT&DTE? 
The spec state:
> When the SDT bit is set to 1 by an explicit CSR write, the SIE (Supervisor Interrupt Enable) bit is cleared to 0. This clearing occurs regardless of the value written, if any, to the SIE bit by the same write. The SIE bit can only be set to 1 by an explicit CSR write if the SDT bit is being set to 0 by the same write or is already 0.
> When menvcfg.DTE is zero, the implementation behaves as though Ssdbltrp is not implemented. When Ssdbltrp is not implemented sstatus.SDT, vsstatus.SDT, and henvcfg.DTE bits are read-only zero. When henvcfg.DTE is zero, the implementation behaves as though Ssdbltrp is not implemented for VS-mode and the vsstatus.SDT bit is read-only zero.

**Comment by aswaterman** [comment]
This repo contains a simulator.  Filing issues makes sense if you think there's a bug in the simulator.  If you have questions about the spec, please use a different forum, e.g. emailing the tech-privileged mailing list.
