### ISSUE TITLE
Does execute log equals to commit log

### ISSUE THREAD

**Issue by Ye-Jinhong** [riscv/riscv-isa-sim#1865]
Hi, I am new here, I am confused that execute log print with `-l` option is the same with `--log-commits`?
I mean, is the execute log contains **speculative** path's instructions that executed?

**Comment by aswaterman** [comment]
Spike is just an ISA interpreter, so there is no concept of speculative execution in this context.  `-l` and `--log-commits` perform similar functions, with the latter being more complete.

**Comment by Ye-Jinhong** [comment]
Thanks very much!!! I am going to only print branch inst for further analyzing, so there should not any "wrong" inst.

**Comment by aswaterman** [comment]
You're welcome, @Ye-Jinhong!
