### ISSUE TITLE
Questions about the cross-page store

### ISSUE THREAD

**Issue by Anzooooo** [riscv/riscv-isa-sim#1867]
I noticed that in the code, there is special handling for cross-page store when misaligned access is enabled.

https://github.com/riscv-software-src/riscv-isa-sim/blob/7812eabb441eaf2067d07636a382eca622e48814/riscv/mmu.cc#L299-L313

It seems that this is splitting a single cross-page store into two separate store operations.
I call them the `low page` and the `high page`.
If the low-page store does not trigger an exception and can be accessed normally, the data of the low-page store will be written directly to memory. If the high-page store triggers an exception (such as a page fault exception), a trap will be triggered using the address of the high-page store . However, at this point, the data of the low-page store has already been written to memory.

Could you please confirm if my understanding of the code is correct?
If it is, may I ask if it adheres to the standards? Is it permissible for a single instruction to partially affect the memory?

**Comment by aswaterman** [comment]
Your understanding is correct, and this is legal in the ISA.  See e.g. https://github.com/riscv/riscv-isa-manual/blob/43316888612be083d3fb9624165b42d8b85c965f/src/machine.adoc#L3273-L3275

(That text is about PMP, not paging, but the same principle applies.)
