### ISSUE TITLE
dcsr.debugver field default value

### ISSUE THREAD

**Issue by Madman-Hugo** [riscv/riscv-isa-sim#1878]
Spike’s dcsr.xdebugver is 1 while spec is 0/4/15
<img width="599" alt="7f44697577187f009e1594e76444cfdd" src="https://github.com/user-attachments/assets/0f476017-f23f-4bba-89a3-bb4f436972b0" />

**Comment by aswaterman** [comment]
It appears that @YenHaoChen accidentally introduced this bug in ec292be4fdac9685c9d6f2f209b73743c2e573f7.

Prior to that change, Spike defined this field to occupy bit positions 31:30, and so inserting a 1 into that position was equivalent to encoding the value 4 in bit positions 31:28.  After the change, the field was redefined to occupy bit positions 31:28, but the value was not changed from 1 to 4.

**Comment by aswaterman** [comment]
Fixed, thanks for pointing this out.
