### ISSUE TITLE
How to run a c code when the code is compiled with -S ?

### ISSUE THREAD

**Issue by nikita890-art** [riscv/riscv-isa-sim#780]
I want the ASM file for my c code. Hence when compiling, I use -S, this is because I want to do some modifications to the ASM file and then check how the output changes when I execute using spike.
but when I execute it, it says,
unable to open ELF file!
This does not happen when I compile without -S but I need the asm file as I want to make changes to it to check what the outout will be.
How can I execute the program without getting the above error?

**Comment by TommyMurphyTM1234** [comment]
An ASM file is not an executable file.
Spike expects a linked ELF file.
If you're using gcc -S to generate the intermediate ASM files from C code files and then modifying the generated ASM (why?) then you still need to assemble and link the ASM file(s) to create an ELF file that Spike can work with.
Please describe in more detail exactly what you're doing and trying to do.
But this sounds more like confusion about how to use the tools than a Spike issue per se.

**Comment by scottj97** [comment]
Closing as not a Spike issue.
