### ISSUE TITLE
A bug about writing scause

### ISSUE THREAD

**Issue by wzy971210** [riscv/riscv-isa-sim#803]
Hi!
There's a bug about writing scause. 
Since it is a WLRL csr, only the supported exception codes can be written. 
However when I try to write a random value to scause and read it then, the return value is just the value of write. The following pictures explain the problem.
![image](https://user-images.githubusercontent.com/44627319/133429338-839733df-9d43-4ebb-9087-a8d7ffe8cbe0.png)
![image](https://user-images.githubusercontent.com/44627319/133429509-e8117893-bf57-43ca-a4e6-8363af669b61.png)

**Comment by scottj97** [comment]
The privileged spec says about scause:

> The Exception Code is a WLRL field. It is required to hold the values 0–31 (i.e., bits 4–0 must be implemented), but otherwise it is only guaranteed to hold supported exception codes.

It does not say that only the supported exception codes can be written -- in fact it explicitly requires that some of the unsupported exception codes (e.g. 10 and 11) be writable.

I see no issue here.

**Comment by aswaterman** [comment]
Agreed with Scott.  The behavior you described corresponds to WARL, not WLRL.

**Comment by wzy971210** [comment]
Thanks, I misunderstood before.
So for the WLRL csr, software is needed to ensure the value of write is legal. If an illegal value is written, it still can be read since hardware will not limit the behavior of write.
And for WARL csr, only the legal value can be read whether the the write is legal or not.

**Comment by aswaterman** [comment]
For WLRL, hardware _might or might not_ limit the behavior of the write.  So e.g. it would be legal for HW to implement WLRL like Spike does, or it would be legal to implement WLRL using WARL instead.
