### ISSUE TITLE
Is it possible to access physical memory in spike from a user program?

### ISSUE THREAD

**Issue by Srijith-r2** [riscv/riscv-isa-sim#811]

**Comment by aswaterman** [comment]
It depends on how the privileged software has configured memory protection.  If using `pk`, the answer is "no, not directly": all user accesses go through page-based address translation.  If using different privileged software that has set up the PMP registers permissively, and has not enabled paging, then U-mode can access physical memory directly.

**Comment by Srijith-r2** [comment]
> It depends on how the privileged software has configured memory protection. If using `pk`, the answer is "no, not directly": all user accesses go through page-based address translation. If using different privileged software that has set up the PMP registers permissively, and has not enabled paging, then U-mode can access physical memory directly.

Yes... am using pk. Any idea how could i do it with pk?

**Comment by aswaterman** [comment]
That would involve rewriting large parts of pk.  You're probably better off not using pk at all, running a bare-metal program instead, as with the programs in https://github.com/riscv-software-src/riscv-tests
