### ISSUE TITLE
New release tag since 1.0.0

### ISSUE THREAD

**Issue by r-value** [riscv/riscv-isa-sim#817]
`spike` is now being packaged for Arch Linux, but I found that the release `1.0.0` is too old to be built and packaged now.

Since release `1.0.0` is now 920 commits behind the current `master` branch, could you please make a new release tag, just to update the package?

**Comment by aswaterman** [comment]
Good point.  I'd like to wait until @scottj97's massive refactoring is complete and well tested, then we will cut another release.  Hopefully that means in the next month or so.

**Comment by r-value** [comment]
@aswaterman Any updates?

**Comment by aswaterman** [comment]
@scottj97 any concerns about making a 1.1.0 release with current contents?

**Comment by scottj97** [comment]
Doesn't seem very stable lately, but maybe it's never stable. I have no concerns.

**Comment by aswaterman** [comment]
True enough.

**Comment by aswaterman** [comment]
https://github.com/riscv-software-src/riscv-isa-sim/releases/tag/v1.1.0
