### ISSUE TITLE
L1 and L2 caches in spike

### ISSUE THREAD

**Issue by msingla403** [riscv/riscv-isa-sim#824]
There is cache simulator available which displays cache stats on running a program. But is this cache actually used in the  working? 

I believe there is separate Icache present in mmu.h https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/mmu.h#L400 And rest all memory accesses are directly made to ram (using mmio functions). 

Please help me in understanding the cache model this simulator is using. Thanks.

**Comment by aswaterman** [comment]
Run `spike --help` to see info about cache models.  They're very coarse, but they're still useful for basic experimentation.

The line you quoted in `mmu.h` is something entirely different.  Spike uses an internal cache to speed up its own instruction fetch.
