### ISSUE TITLE
issues in installing spike

### ISSUE THREAD

**Issue by sundas56** [riscv/riscv-isa-sim#828]
while installing spike in ubuntu using RISCV 64 bit gnu toolchain,  it gives me this error 
make: *** No targets specified and no makefile found.  Stop.

**Comment by aswaterman** [comment]
Sounds like you didn't run `make` in the same directory you ran `configure`.  See https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/README.md#build-steps

**Comment by sundas56** [comment]
I'm running configure and make both in build directory

**Comment by aswaterman** [comment]
Did `configure` actually succeed?  If you `ls` you should see that a `Makefile` was created.

**Comment by scottj97** [comment]
@sundas56 please close this issue (and #827) if you don't want or need any more help.

**Comment by scottj97** [comment]
Closing due to lack of followup from OP.
