### ISSUE TITLE
Adding new register

### ISSUE THREAD

**Issue by msingla403** [riscv/riscv-isa-sim#829]
I added a new register `mkeyxor` in [riscv/processor.h](https://github.com/riscv-software-src/riscv-isa-sim/blob/e2691f0a53e083b7495b6aa50634ac22d464369b/riscv/processor.h) (similar to `satp`). Then added below lines in [riscv/encoding.h](https://github.com/riscv-software-src/riscv-isa-sim/blob/e2691f0a53e083b7495b6aa50634ac22d464369b/riscv/encoding.h). 
```
#define CSR_MKEYXOR 0x308
DECLARE_CSR(mkeyxor, CSR_MKEYXOR)
```
`0x308` was not assigned to anything before. Added same above two lines in [machine/encoding.h](https://github.com/riscv-software-src/riscv-pk/blob/b7ee9734776123c34a8c0d37fa981169521614ad/machine/encoding.h) of pk. 

But on launching interactive debug mode, I am not able to access this register.
```
$ spike -d pk hello
: reg 0 mkeyxor
: 
```

Is this correct way of adding register?

**Comment by scottj97** [comment]
You also need to instantiate an object for it (some child class of `csr_t`) and put it into the `csrmap[]` in `state_t::reset()`.

As for which class to use, you might be able to use `basic_csr_t` (if it's an XLEN-width register) or `masked_csr_t` if it's narrower. If you need additional access restrictions (enabling this CSR only if a certain extension is configured, for example) then you need to derive a new class and override method `verify_permissions()`.

Let me know if I can help. I'm happy to review your changes.

**Comment by msingla403** [comment]
I am using version of [25th May](https://github.com/riscv-software-src/riscv-isa-sim/tree/e2691f0a53e083b7495b6aa50634ac22d464369b) `e2691f0a53e083b7495b6aa50634ac22d464369b`. I am sorry, I should have told this earlier.

Correct file links [riscv/encoding.h](https://github.com/riscv-software-src/riscv-isa-sim/blob/e2691f0a53e083b7495b6aa50634ac22d464369b/riscv/encoding.h) and [riscv/processor.h](https://github.com/riscv-software-src/riscv-isa-sim/blob/e2691f0a53e083b7495b6aa50634ac22d464369b/riscv/processor.h).

The structure in earlier commits look different and there is no `csrmap` in `state_t::reset()`. Although I have added a line `  mkeyxor = 0;`  in `state_t::reset()` (similar to `satp`).

Thanks.

**Comment by scottj97** [comment]
Then you need to add appropriate clauses in `processor_t::get_csr()` and `processor_t::set_csr()` to read and write that new register.

But if I were you, I'd update to a newer Spike first; otherwise you will have to redo all this work later when you do update, because the CSR implementation has completely changed since May 25.

**Comment by msingla403** [comment]
Oh okay, Actually I was not able to compile the latest version on my macOS. Apparently the problem was due to boost library. So I went to work on commit which did not require boost library.

Error:
```
g++ -L. -L/usr/local/lib  -Wl,-rpath,/opt/riscv/lib  -o spike spike.o  libspike_main.a  libriscv.a  libdisasm.a  libsoftfloat.a  libfesvr.a  libfdt.a -lpthread -lpthread  -lboost_system-mt -lboost_regex-mt
Undefined symbols for architecture x86_64:
  "__Z11fdt_getpropPKviPKcPi", referenced from:
      __ZL14check_cpu_nodePvi in libriscv.a(dts.o)
      __ZL22fdt_get_node_addr_sizePviPyPmPKc.constprop.0 in libriscv.a(dts.o)
      __Z18fdt_parse_mmu_typePviPc in libriscv.a(dts.o)
  "__Z14fdt_size_cellsPKvi", referenced from:
      __ZL22fdt_get_node_addr_sizePviPyPmPKc.constprop.0 in libriscv.a(dts.o)
  "__Z15fdt_path_offsetPKvPKc", referenced from:
      __Z14fdt_get_offsetPvPKc in libriscv.a(dts.o)
  "__Z16fdt_next_subnodePKvi", referenced from:
      __Z20fdt_get_next_subnodePvi in libriscv.a(dts.o)
  "__Z17fdt_address_cellsPKvi", referenced from:
      __ZL22fdt_get_node_addr_sizePviPyPmPKc.constprop.0 in libriscv.a(dts.o)
  "__Z17fdt_first_subnodePKvi", referenced from:
      __Z21fdt_get_first_subnodePvi in libriscv.a(dts.o)
  "__Z17fdt_parent_offsetPKvi", referenced from:
      __ZL22fdt_get_node_addr_sizePviPyPmPKc.constprop.0 in libriscv.a(dts.o)
  "__Z29fdt_node_offset_by_compatiblePKviPKc", referenced from:
      __Z15fdt_parse_clintPvPyPKc in libriscv.a(dts.o)
  "__ZN5boost24scoped_static_mutex_lockC1ERNS_12static_mutexEb", referenced from:
      __ZN5boost16cpp_regex_traitsIcE16get_catalog_nameB5cxx11Ev in libriscv.a(interactive.o)
      __ZN5boost13re_detail_50010regex_dataIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEC2Ev in libriscv.a(interactive.o)
  "__ZN5boost24scoped_static_mutex_lockD1Ev", referenced from:
      __ZN5boost16cpp_regex_traitsIcE16get_catalog_nameB5cxx11Ev in libriscv.a(interactive.o)
      __ZN5boost13re_detail_50010regex_dataIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEC2Ev in libriscv.a(interactive.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [Makefile:349: spike] Error 1
```

I am using GNU-GCC for compilation.

**Comment by scottj97** [comment]
Try this [workaround](https://github.com/riscv-software-src/homebrew-riscv/pull/71#issuecomment-930809706)

**Comment by msingla403** [comment]
Thanks, it works. My issue is resolved.
