### ISSUE TITLE
Compiled program with RV64I does not run under Spike with the --isa=rv64i option but with extensions it does

### ISSUE THREAD

**Issue by Nado15** [riscv/riscv-isa-sim#833]
Hello,

I compiled a bare metal program with -march=rv64i -mabi=lp64 -nostdlib -mcmodel=medany and get the following error
"trap_instruction_address_misaligned" while running spike with --isa=rv64 option.

On this picture you can see it. Check the adress **0x000000007000006c**,

![2](https://user-images.githubusercontent.com/20690763/137405441-7206d8a0-21e9-4af8-adae-7cfc533b44b6.png)

Here is a objdump of my program, as you can see its a rv64i base instruction

This function is from libgcc.a which I linked to my program, because I need a softfloat library.

![1](https://user-images.githubusercontent.com/20690763/137405452-a890a824-dd4c-4b9c-be50-4e5a71bf26f9.png)

Meanwhile when I run spike with all extensions it works but as you can see spikes debugger interprets this instruction as an instruction from the C extension(?).

![3](https://user-images.githubusercontent.com/20690763/137405457-bf1fafbc-6b34-4b75-afd0-68e6cb0ff2de.png)

I am using riscv64-unknown-elf-gcc, have my own linker script and use spike bare metal

**Comment by scottj97** [comment]
As you can see in the disassembly, those are compressed (16-bit) instructions. It looks like the C library was compiled with the C extension enabled, which is the default. You will need to rebuild libgcc with the appropriate isa string.

Not a Spike issue.

**Comment by Nado15** [comment]
Darn! You are right, thank you!
