### ISSUE TITLE
How to set mstatus in order to run V-extension

### ISSUE THREAD

**Issue by hushenwei2000** [riscv/riscv-isa-sim#835]
I'm writing program with rvv1.0. But when I run:
```
spike --isa=rv64gcv my-vadd
```
It will raise illegal_instruction at any vector instruction including vsetvli, vadd, vmv.v.x, ect..  
When I try to debug to see mstatus, it's like:
```
core   0: 0x0000000080000180 (0x02110757) vadd.vv v14, v1, v2
core   0: exception trap_illegal_instruction, epc 0x0000000080000180
: reg 0 mstatus
0x0000000a00000000
```
And I know that the mstatus[10:9] should be set to non-zero to enable vector.
But I cant use `csrw` instruction to set mstatus because it raise illegal_instruction.
MSTATUS_VS is defined in `decoding.h` like `#define MSTATUS_VS          0x00000600`.  
How can I solve this problem ?

**Comment by scottj97** [comment]
CSRW to mstatus is the way. Why does that take an illegal instruction exception? Is your code not running in M-mode?

**Comment by hushenwei2000** [comment]
> CSRW to mstatus is the way. Why does that take an illegal instruction exception? Is your code not running in M-mode?

No, I didn't use `--priv` option, so default it it `MSU`

**Comment by scottj97** [comment]
You're going to have to give us more information then. When Spike comes out of reset, CSRW to mstatus will not take any exception.

**Comment by scottj97** [comment]
Closing due to lack of followup from OP.
