### ISSUE TITLE
PMP related differences in old version of spike Vs. latest

### ISSUE THREAD

**Issue by sammy17** [riscv/riscv-isa-sim#836]
I have been using an old version of spike and now trying to update the spike version I use to the latest. 
I get different traces/ control flow when I run the same program in the old spike Vs the latest. 
I believe this difference is due to PMP implementation differences. 

I initialize the PMP CSRs are below in the beginning of the program. Following is the trace with the latest spike.
```
core   0: 0x0000000080000060 (0x0010029b) addiw   t0, zero, 1
core   0: 3 0x0000000080000060 (0x0010029b) x 5 0x0000000000000001
core   0: 0x0000000080000064 (0x03529293) slli    t0, t0, 53
core   0: 3 0x0000000080000064 (0x03529293) x 5 0x0020000000000000
core   0: 0x0000000080000068 (0xfff28293) addi    t0, t0, -1
core   0: 3 0x0000000080000068 (0xfff28293) x 5 0x001fffffffffffff
core   0: 0x000000008000006c (0x3b029073) csrw    pmpaddr0, t0
core   0: 3 0x000000008000006c (0x3b029073) c944_pmpaddr0 0x001fffffffffffff
core   0: 0x0000000080000070 (0x01f00293) li      t0, 31
core   0: 3 0x0000000080000070 (0x01f00293) x 5 0x000000000000001f
core   0: 0x0000000080000074 (0x3a029073) csrw    pmpcfg0, t0
core   0: 3 0x0000000080000074 (0x3a029073) c928_pmpcfg0 0x000000000000001f
```
Following is the trace when I execute the same in my current spike.
```
core   0: 0x0000000080000060 (0x0010029b) [0x0000000a00000000] 00 addiw   t0, zero, 1
3 0x0000000080000060 (0x0010029b) x 5 0x0000000000000001
core   0: 0x0000000080000064 (0x03529293) [0x0000000a00000000] 00 slli    t0, t0, 53
3 0x0000000080000064 (0x03529293) x 5 0x0020000000000000
core   0: 0x0000000080000068 (0xfff28293) [0x0000000a00000000] 00 addi    t0, t0, -1
3 0x0000000080000068 (0xfff28293) x 5 0x001fffffffffffff
core   0: 0x000000008000006c (0x3b029073) [0x0000000a00000000] 00 csrw    pmpaddr0, t0
3 0x000000008000006c (0x3b029073) c944_pmpaddr0 0x000000003fffffff
core   0: 0x0000000080000070 (0x01f00293) [0x0000000a00000000] 00 li      t0, 31
3 0x0000000080000070 (0x01f00293) x 5 0x000000000000001f
core   0: 0x0000000080000074 (0x3a029073) [0x0000000a00000000] 00 csrw    pmpcfg0, t0
3 0x0000000080000074 (0x3a029073) c928_pmpcfg0 0x000000000000001f
```
**I see a difference in the value that gets written in pmpaddr0**

The program initializes the user mode and then jumps to user mode with a mret. At this moment latest spike gives a **trap_instruction_page_fault** exception while the old spike starts executing the user-mode program without any issue, as expected. 

Since the latest spike causes an exception in mret, it gets stuck in an infinite loop.

I wanted to know what are the changes between old Vs latest spike that can be causing these differences and how do I correct it. 

I have attached the trace logs of both old and new executions and the elf file of the program. 
Please let me know if you need more information
[new_spike.log](https://github.com/riscv-software-src/riscv-isa-sim/files/7356908/new_spike.log)
[old_spike.log](https://github.com/riscv-software-src/riscv-isa-sim/files/7356909/old_spike.log)
[test.zip](https://github.com/riscv-software-src/riscv-isa-sim/files/7356910/test.zip)

**Comment by scottj97** [comment]
I recently redid all the CSR implementation in Spike, including pmpaddr0. I will look into this.

Can you tell me what commit numbers (git hashes) you were using for the old and new Spike?

And what exact command line you ran? --isa string, etc.

**Comment by sammy17** [comment]
Unfortunately, I don't have the commit version of the old spike that I am using (just have a copied repo with git info removed) but the new one is b8d27b6ac039abc1c31b3caea4342cadfb682ea3.
Please let me know if I can find the commit version from any of the source files in the repo. 

I used the below command for both without any --isa flag:
`spike -l --log-commits test.elf  `

**Comment by sammy17** [comment]
I just randomly checked few commits and I can see program exits correctly with this commit 9bfb43c668848a4850d5805b9adb8ad18e7f43b6

**Comment by scottj97** [comment]
I tried both 9bfb43c and b8d27b6 and I see the same pmpaddr0 in both:

```
core   0: 0x000000008000006c (0x3b029073) csrw    pmpaddr0, t0
core   0: 3 0x000000008000006c (0x3b029073) c944_pmpaddr0 0x001fffffffffffff
```

Which looks correct to me. I don't know why you were seeing 0x3fffffff previously. Could you possibly have modified MAX_PADDR_BITS?

I see the endless page fault, but PMP causes access fault, not page fault. The page fault is due to #752. Change 80be4e21c3af7fe2966788ce538d3e3c3b0d60e3 is the first that fails, which tells me there's a problem in the page tables in your test. The non-leaf PTEs apparently have one or more of the d/a/u bits set. The spec requires them to be 0. See the [bug report](https://github.com/riscv-software-src/riscv-tests/issues/352) that led to #752 for an explanation of the spec requirement.

**Comment by sammy17** [comment]
I can confirm that my old version has MAX_PADDR_BITS set to 32 which is probably causing this issue. Thanks for pointing out. 
I will go through other issues you mentioned and get back to you, thank you again!

**Comment by sammy17** [comment]
I analyzed the issue with the information you gave and it is due to the D/A/U bits set in my non-leaf PTE.  I will close this issue since the cause for the difference is clear now.   
Thank you for the help.
