### ISSUE TITLE
Refactor the disassembly implementation to improve performance

### ISSUE THREAD

**Issue by zhongchengyong** [riscv/riscv-isa-sim#837]
The disassemble implementation maybe slow since the most instruction(disasm_insn_t*) is stored in chain[HASH_SIZE], it take more time to compare in disassembler_t::lookup.([https://github.com/riscv-software-src/riscv-isa-sim/blob/master/disasm/disasm.cc](function lookup and add_insn))
I'll PR if you also think that improving performance is valuable.
My preliminary plan is setting **chain** array length to 128, which is hashed by 7-bits opcode, when lookup, use the lowest 7-bits to find the proper chain element and compare. RVC instructions will be treated specially since it only use the lowest 2-bits for opcode. It will reduce the comparisons for disassemble.

**Comment by aswaterman** [comment]
I'd strongly prefer to keep the lookup pattern agnostic to the instruction encoding scheme.  It's OK if we optimize for standard RISC-V encodings, but the assembler should still function correctly when custom instructions use incompatible encoding schemes.

I was going to describe an implementation that satisfies my requirements, but writing the code seemed easier than describing it: 1453b3588bdb6f42767c0c2ee2ffcd70ddf97afa

For my test case, the average number of comparisons per lookup is now approximately 3.2.  But the disassembler still works correctly if people invent new instruction formats.

I also sped up some of the other hot spots in the disassembly routines.  Overall it's around 2x faster now.

**Comment by zhongchengyong** [comment]
Cool! But maybe it's better to set the HASH_SIZE to 127 instead of 255? Since the lowest 8-bits in "insn & MASK1" and "insn & MASK2" result won't be greater than 0x7f, if chain array size is set to 256, then the index between 128 and 254 is wasted.

**Comment by aswaterman** [comment]
Compressed instructions use the other hash function, so the space is not wasted.

**Comment by zhongchengyong** [comment]
Yeah, you're right.
