### ISSUE TITLE
How to change the values of VLEN,ELEN and SLEN

### ISSUE THREAD

**Issue by lifei0919** [riscv/riscv-isa-sim#841]
Hey!   I am a student who is interested in RISCV vector. Now we have a problem
I have spike installed, but now I want to changed the values of vlen, elen, and slen to 256,256,256 respectively, but when I look at the vector registers (vreg 0 2) it still shows vlen=128bits and elen=64bits.My modification method is as follows:
First, I changed vlen, elen, and slen to 256 in the config.h file in the build directory, then saved and quit.
Next, re-make in the build directory.
finally,Sudo make install.
After completing the above steps, I found that their values were not successfully modified.

**Comment by chihminchao** [comment]
You could adjust the vector config by command option --varch="vlen:256,elen:256,vstartalu:0".   slen has been removed in 1.0-draft.

**Comment by lifei0919** [comment]
Thank you, that's all.
But when I set vlen=256 and elen=256, I run my following program

- vsetvli a2, a3, e64, m1
- vl1re64.v v2, (a1)

When I check vector register v2 through vreg 0 2, there is nothing in it and 0x0000000000000000 is not displayed
Before I set ，then vlen=128, elen=64
I run the following command

- vsetvli a2, a3, e64, m2
- vl2re64.v v2, (a1)

Vreg 0 2 and Vreg 0 3 show that v2 and V3 hold two doublewords respectively.So now I don't know what went wrong, whether I made a mistake with vreg 0 2.

**Comment by chihminchao** [comment]
hmmm,  the other issue may be the elen:256.  For spike implementation, it only support elen up to 64.

**Comment by lifei0919** [comment]
Thank you for your answer. It's very useful

**Comment by lifei0919** [comment]
Good evening, chihminchao
why did the floating point register become 128-bit after I set the vector register to 256bit with this compilation option vlen=256 and elen=256.
When I look at the contents of the floating point register, it looks like this:

: freg 0 fs7
0xffffffffffffffffbf21ec601241edd7
: freg 0 fs6
0xffffffffffffffffbf4076137798f465
: freg 0 fa7
0xffffffffffffffffbf630e04b3f990e8
