### ISSUE TITLE
Vector vmv1r.v erroneously ignores SEW

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-sim#857]
The spec for vmv1r.v says:

> The instructions operate as if EEW=SEW, EMUL = NREG, effective length evl= EMUL * VLEN/SEW.

But the [vmv1r.v source](https://github.com/riscv-software-src/riscv-isa-sim/blob/f1bc56264ed214ee941b3a601a693ab655724f52/riscv/insns/vmvnfr_v.h) does not seem to take SEW into account at all.

When vstart=1, it should start the copy from the second element according to SEW (right?), but seems to always start from the second byte, as if SEW=8.

cc @chihminchao

**Comment by aswaterman** [comment]
I agree that the whole-register moves should report vstart in terms of SEW-sized elements, not bytes.  I think the reason I haven't observed this is that the implementation I had been working on doesn't support interruption/restart of arithmetic, only of loads & stores.

**Comment by scottj97** [comment]
Fixed by #959
