### ISSUE TITLE
delegable_ints excludes machine interrupts seemingly arbitrarily

### ISSUE THREAD

**Issue by p0llard** [riscv/riscv-isa-sim#864]
https://github.com/riscv-software-src/riscv-isa-sim/blob/37b7204920e1cf5adbdc6241fb20192c3a2ee495/riscv/csrs.cc#L608

From my reading of 20190608-Priv-MSU-Ratified, there doesn't seem to be anything that would _forbid_ Machine Interrupts from being delegated, so it should be possible to set `mideleg[i]` for `i \in {11, 7, 3}`; of course the implementation is allowed not to support this.

It seems that `MIP_MSIP | MIP_MTIP | MIP_MEIP` are only ORed into `all_ints` and have thus been consciously excluded from `delegable_ints`.

Presumably either:
1. my reading of the spec is wrong
2. there's a good reason why an implementation might want to forbid delegation of Machine Interrupts, and Spike has chosen to follow this

It seems the fu740 doesn't support this delegation, so I'm leaning towards 2, but I can't really see why this is.

I appreciate this is not necessarily the right forum for a discussion on this, but at least here I can point to a specific line of code!

**Comment by aswaterman** [comment]
The reasoning goes the other way: there isn't a good reason to delegate those interrupts, and so Spike takes the same minimalist approach we expect the majority of HW implementations to take.  In practice, this simplifies verification/cosimulation a little bit.

**Comment by p0llard** [comment]
@aswaterman fair enough, closing since this clearly isn't an oversight.

For context, I want to delegate the Machine Timer Interrupt to Supervisor mode; it seems that most silicon doesn't break out a Supervisor Timer line, so it seems that if one wants the Supervisor to receive Timer interrupts then one must "soft delegate" by having the `mtvec` raise `STIP`.

It seems that it would be more efficient to have the hardware delegate here, especially in the case where there's nothing actually running in Machine mode (i.e. no SBI)?

My assumption here is that were we to delegate the Machine Timer Interrupt then the Supervisor would receive a _Supervisor_ Timer Interrupt, I'm not sure it makes sense for the Supervisor to receive a _Machine_ Timer Interrupt since it can't access MTIP/E; there was some discussion about this in https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/iJqwTw2hIRk/, but I'm not sure the spec actually makes this clear.

**Comment by aswaterman** [comment]
The recently ratified Sstc extension offers a directly usable supervisor timer interrupt.  The approach is a little different than what you're suggesting, because it adds a second comparator, rather than stealing M-mode's.
