### ISSUE TITLE
Various traps fail to properly set mstatus.GVA=1

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-sim#872]
There are several special cases where on a trap, Spike will erroneously set `mstatus.GVA=0` when the value written into `mtval` is a guest virtual address. It should set `mstatus.GVA=1` according to this requirement from the spec section 5.4.1:

> Field GVA (Guest Virtual Address) is written by the implementation whenever a trap is taken into M-mode. For any trap (breakpoint, address misaligned, access fault, page fault, or guest-page fault) that writes a guest virtual address to mtval, GVA is set to 1. For any other trap into M-mode, GVA is set to 0.

1. [Debug trigger traps](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/execute.cc#L332) on HLV/HLVX/HSV or load/store with MPRV=1 and MPV=1 (in #850 I fixed only normal loads & stores)
2. Misaligned [LR](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/mmu.h#L262-L266) or [SC](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/mmu.h#L272-L276) access fault when MPRV=1 and MPV=1
3. MMIO [load](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/mmu.cc#L153) or [store](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/mmu.cc#L182) where the device detects an access fault, on HLV/HLVX/HSV or load/store with MPRV=1 and MPV=1
4. [LR to I/O space](https://github.com/riscv-software-src/riscv-isa-sim/blob/c4fdc8fe95e497ab6e107117a7de47ec40e7de7d/riscv/mmu.h#L256), when MPRV=1 and MPV=1

**Comment by scottj97** [comment]
To solve this robustly, I am thinking of a data structure that holds info about the desired access:
* virtual address
* effective mode (including 2 bits of privilege and 1 bit of V)
* special cases that alter permissions like HLVX

Then we pass around this data structure instead of a simple virtual address.

This would replace things like `xlate_flags` with its `RISCV_XLATE_VIRT` and `RISCV_XLATE_VIRT_HLVX`.

**Comment by aswaterman** [comment]
That sounds like a sound and more robust approach to me, Scott.

**Comment by rbuchner-aril** [comment]
@aswaterman I believe this should be closed.
