### ISSUE TITLE
RISCV tools directory mentioned

### ISSUE THREAD

**Issue by peteralieber** [riscv/riscv-isa-sim#888]
In the main README, it mentions the path to the riscv-tools path as a prefix.  The riscv-tools repository is out of date, and has old versions tagged for submodules... is this still the expected way to compile and use SPIKE and pk?

**Comment by scottj97** [comment]
The README says:

> We assume that the RISCV environment variable is set to the RISC-V tools install path.

I don't see where it mentions anything about the [riscv-tools repo](https://github.com/riscv-software-src/riscv-tools).

Even without using the riscv-tools repo, you still need a RISC-V compiler, which is where $RISCV points to.

**Comment by peteralieber** [comment]
Why do you need a RISC-V compiler to build spike? 

My real question is, what is expected in $RISCV? I got spike compiling and running, but I'm not sure I needed anything in my $RISCV path (although I did have pk and others from the riscv-tools repo left over).

**Comment by aswaterman** [comment]
You don't need a RISC-V compiler to build or run Spike.  The README includes a tutorial for building and running a simple program, which of course does require a RISC-V compiler (and C library and ...).

**Comment by peteralieber** [comment]
Yes, I finally got my tool chain working. I think it was just misleading a bit for me, and got me thinking that there was something else needed to build Spike inside the mysterious riscv-tools location (which isn't really defined in this readme). In searching for this answer, I assumed it was talking about the riscv-tools repository... I understand what you meant by this now. Thanks for the clarification.
