### ISSUE TITLE
 running all zba zbb zbc zbs in RV32

### ISSUE THREAD

**Issue by lico614257** [riscv/riscv-isa-sim#906]
How is Spike compatible with running zba zbb zbc zbs? Like the old version of Spike, I was able to use --isa=rv32imafcb, but how to include all the ZB * in the new version while running?

**Comment by eflaner** [comment]
> how to include all the ZB * in the new version while running

For those that are ratified(Zba, Zbb, Zbc and Zbs) you can use `--isa=rv32imafc_Zba_Zbb_Zbc_Zbs`
for rest of them you can specify `--isa=rv32imafc_Xbitmanip`
