### ISSUE TITLE
Some vmadc and vmsbc instructions disassemble with "args unknown"

### ISSUE THREAD

**Issue by noahsherrill** [riscv/riscv-isa-sim#916]
Disassembly of vmadc.vi, vmadc.vv, vmadc.vx, vmsbc.vv and vmsbc.vx prints "args unknown" where the operands should be. I think this is due to the workings of the DEFINE_VECTOR_V(V|X|I)M macros. These macros appear to add two instructions with the same parameters, e.g. vmadc.vvm, rather than two distinct variants, as appears to be the intent, e.g. vmadc.vvm and vmadc.vv. This results in the entries without the "m" suffix being omitted.

There are a few caveats I want to mention. This was discovered using a modified version of Spike 7dbb7c353ff8877a0d194845acf298c7c3f6f961. I don't have an easy way to test the issue in an unmodified current version of Spike, so I am not completely certain that this issue exists in the latest version of Spike. That said, the source code that I believe is causing the issue looks the same in the latest version.

**Comment by aswaterman** [comment]
Thanks for the bug report and the analysis; fixing.
