### ISSUE TITLE
make error installing spike 

### ISSUE THREAD

**Issue by hasver** [riscv/riscv-isa-sim#924]
Trying to install spike from the commands in the readme file. I encountered this error: 
In file included from ../riscv/mmu.h:6:0,
                 from ../riscv/insn_template.h:4:
../riscv/insns/sunpkd810.h: In function ‘reg_t rv32i_sunpkd810(processor_t*, insn_t, reg_t)’:
../riscv/decode.h:242:60: error: expression cannot be used as a function
 #define get_field(reg, mask) (((reg) & (decltype(reg))(mask)) / ((mask) & ~((mask) << 1)))

and then the terminal continues to print lots of stuff until: 

cc1plus: warning: unrecognized command line option "-Wno-nonportable-include-path" [enabled by default]
make: *** [sunpkd810.o] Error 1

What could be the problem?

**Comment by aswaterman** [comment]
It sounds like you are using an old compiler.  Unfortunately, we do not have the resources to support this kind of issue.
