### ISSUE TITLE
avoid printing hstatus when hypervisor not enabled

### ISSUE THREAD

**Issue by neelgala** [riscv/riscv-isa-sim#932]
I am using the following command:
```
spike --log ref.dump --log-commits --priv=msu --isa=rv64ima rv64im-Illegal-p.elf
```
What I observe is that when sret is executed the following entry is is made in ref.dump

```
core   0: 1 0x0000000080000264 (0x10200073) c1536_hstatus 0x0000000200000000 c768_mstatus 0x0000000a001000a8
```

Is it possible to print hstatus in the above line only when hypervisor is enabled via the cli --isa arg ? Where should I start looking to find a fix for this ?

**Comment by scottj97** [comment]
Fixed in #934
