### ISSUE TITLE
Spike run instruction  lr.w and sc.d, sc.d should fail and return error according to riscv spec, however it success and return 0

### ISSUE THREAD

**Issue by YangGuangRongXian** [riscv/riscv-isa-sim#933]
![lrw_scd](https://user-images.githubusercontent.com/100554547/155933102-26f5d104-b301-4162-8359-935d77aacdf2.JPG)
The sc.d instruction return 0 as yellow rectangle show in the picture.

**Comment by aswaterman** [comment]
For forward progress, it is required that the LR and SC's sizes be equal.  However, there is no requirement that says the SC _must_ fail if the size differs.  See https://github.com/riscv/riscv-isa-manual/blob/a2cf7ea4cbe84f7ec25081cddf7c5462fb0b737a/src/a.tex#L175-L176

You might've seen this statement https://github.com/riscv/riscv-isa-manual/blob/a2cf7ea4cbe84f7ec25081cddf7c5462fb0b737a/src/a.tex#L308-L309 and assumed this was a mandatory failure condition.  In fact, that's just a set of sufficient conditions for forward progress; violating them doesn't guarantee SC failure.

So, Spike is doing something correct here.
