### ISSUE TITLE
Misaligned access

### ISSUE THREAD

**Issue by sawansib** [riscv/riscv-isa-sim#953]
Hello!

As per the previous issues and commits RISCV_ENABLE_MISALIGNED is set to false by default.
But if my code has misaligned accesses and I want behavior matching HW that handles misaligned accesses in HW, then 
1) Does Spike support that? If yes how?
2) Or should I just set RISCV_ENABLE_MISALIGNED?

Regards
Sawan

**Comment by scottj97** [comment]
When you build Spike, add `--enable-misaligned` to the `./configure` step.

It sounds like we need to add something to the README about the configure options.

**Comment by sawansib** [comment]
Thank you for the reply!

What does --enable-misaligned do actually? Does it align the access or create two separate access for the misaligned ones?

Sawan

**Comment by scottj97** [comment]
Instead of taking a misaligned exception, it does a misaligned load/store by doing a series of one-byte load/stores.

**Comment by sawansib** [comment]
Okay! Thank you for your reply it was really helpful.

Sawan

**Comment by sawansib** [comment]
Hi, sorry to re-open this issue. 

As you said that the misaligned load/store is done by a series of one-byte load/stores, do these one-byte loads and stores are real memory operations or some internal Spike workaround for misaligned load/store?

Sawan

**Comment by scottj97** [comment]
I'm not sure what you mean by "real" memory operations...as opposed to what?

It's not a workaround; it's a simple implementation of misaligned load/store.

**Comment by sawansib** [comment]
I mean if you have a bunch of memory operations doing one byte at a time it will increase the total number of memory operations, right? So this is the way it is implemented in a real RISC machine?

**Comment by sawansib** [comment]
Ah okay, thank you for making it clear. 

By "real" I meant Spike is a functional simulator so one load/store should be just one, but when you do the one byte per load/store for a misaligned it will create multiple load/store instead of one.

**Comment by scottj97** [comment]
A real hardware design would do two load/store accesses for misaligned. But there is no functional difference between that and one-per-byte like Spike does, unless you're doing misaligned accesses to memory-mapped devices, which no reasonable software should do.

**Comment by sawansib** [comment]
Thank you!
