### ISSUE TITLE
Spike fails to build on RISC-V machines

### ISSUE THREAD

**Issue by r-value** [riscv/riscv-isa-sim#965]
I tried to build spike for RISC-V but got lots of errors. For example, the macros defined here:
https://github.com/riscv-software-src/riscv-isa-sim/blob/70b7e9ca2d04effda5fe964c968fbbabf72e54d9/riscv/encoding.h#L287
included from:
https://github.com/riscv-software-src/riscv-isa-sim/blob/70b7e9ca2d04effda5fe964c968fbbabf72e54d9/fesvr/dtm.cc#L3
conflicts with:
https://github.com/riscv-software-src/riscv-isa-sim/blob/70b7e9ca2d04effda5fe964c968fbbabf72e54d9/fesvr/dtm.cc#L408

The code nearby clearly won't compile on RISC-V, too.

**Comment by aswaterman** [comment]
Thanks for the bug report.  Fixed.
