### ISSUE TITLE
ePMP support

### ISSUE THREAD

**Issue by rswarbrick** [riscv/riscv-isa-sim#970]
Are there any imminent plans to add [ePMP](https://github.com/riscv/riscv-tee/blob/main/Smepmp/Smepmp.pdf) support to Spike? At lowRISC, we have a processor that supports it and would like to extend Spike to be able to verify things properly.

I know that there is a set of patches for ePMP support at https://github.com/joxie/riscv-isa-sim, but a quick look at the patches suggests these aren't in an upstreamable form.

Is anyone else working on this at the moment, or should we roll up our proverbial sleeves?

**Comment by aswaterman** [comment]
FWIW, I hadn't planned to work on this any time soon, so lowRISC contributing a patch set would be welcome.

**Comment by rswarbrick** [comment]
Great, thanks for getting back to us. We'll start hacking soon.

**Comment by joxie** [comment]
Hi Rupert I have a working fork at https://github.com/joxie/riscv-isa-sim and plan to upstream soon

**Comment by aswaterman** [comment]
@rswarbrick since you have a good idea of our process and expectations, can I ask that you work with @joxie to shepherd this PR?

**Comment by joxie** [comment]
https://github.com/joxie/riscv-isa-sim/tree/epmp is cleaner (without tests, need to find a home for tests)

**Comment by joxie** [comment]
@rswarbrick please let me know the flow to follow for this PR?

**Comment by rswarbrick** [comment]
Well, the first step is probably to fiddle around to get a series of patches rebased cleanly on to the upstream master branch. Once we've got that, we can take a look at the commits that need upstreaming and try to figure out how to chop them up into small PRs that can be merged incrementally. (If you try to do the whole lot at once, it's almost impossible to avoid getting bogged down in interminable reviews in any project that has proper PR reviewing)

**Comment by joxie** [comment]
I created PR #980

**Comment by joxie** [comment]
PR upstreamed, we can close this issue now

**Comment by scottj97** [comment]
Implemented in #983

**Comment by rswarbrick** [comment]
Late to the party but... that's absolutely awesome! Thank you so much for doing this.
