### ISSUE TITLE
Base Address change causing Linker Error

### ISSUE THREAD

**Issue by AayushMisra** [riscv/riscv-isa-sim#989]
Hie,
Debugging using GDB and OpenOCD, mentioned in README. 
In spike.lds linker script, I modified the base address from 0x10010000 to 0x80000000.
The following error was encountered:
`/debugger/ocd_test/rot13.c:8:(.text+0x10): relocation truncated to fit: R_RISCV_HI20 against symbol 'wait' defined in .sdata section in rot13-64.o
collect2: error: ld returned 1 exit status`
Modifying to other lower addresses works fine, can someone help me to understand this issue better,
And can someone direct me to a link to understand RISC-V linker better.

**Comment by aswaterman** [comment]
This is the issue tracker for the Spike simulator. We can’t offer general RISC-V support in this forum.
