### ISSUE TITLE
Benchmarking on Linux

### ISSUE THREAD

**Issue by msingla403** [riscv/riscv-isa-sim#993]
I want to compare the performance of two user programs on Linux **on Spike**. What will be the best way to do that? 

Is `time program` reliable way of comparing performance?

**Comment by scottj97** [comment]
Spike is not a performance model and is not suitable for measuring performance of user programs. You would need a microarchitectural model of an actual hardware CPU to accurately gauge performance of a RISC-V program (absent real hardware, of course).
